import { NEXUS_UPGRADES, SHRINES } from '../config/worldStrategy.js';
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class WorldStrategyHUD{
 constructor(game,world){this.game=game;this.world=world;this.last='';this.root=null;this.modal=null;if(typeof document!=='undefined')this.mount();}
 mount(){const host=document.querySelector('.viewport-wrap')||document.body;this.root=document.createElement('section');this.root.id='worldStrategyHud';this.root.className='world-hud';this.root.innerHTML=`<div class="world-hud-top"><span class="world-tag">WORLD</span><button type="button" data-world="nexus">NEXUS</button><button type="button" data-world="map">MAP</button><button type="button" data-world="run">RUN</button></div><div class="world-hud-body" id="worldHudBody"></div>`;host.appendChild(this.root);this.modal=document.createElement('div');this.modal.className='world-modal hidden';this.modal.innerHTML='<div class="world-modal-card" id="worldModalCard"></div>';host.appendChild(this.modal);this.root.addEventListener('click',e=>{const action=e.target.closest('[data-world]')?.dataset.world;if(action)this.togglePanel(action);});this.modal.addEventListener('click',e=>{const artifact=e.target.closest('[data-artifact]')?.dataset.artifact;if(artifact){this.world.chooseArtifact(artifact);this.hideModal();return;}const wave=e.target.closest('[data-wave-choice]')?.dataset.waveChoice;if(wave){this.world.chooseWave(wave);this.hideModal();return;}const nexus=e.target.closest('[data-nexus-upgrade]')?.dataset.nexusUpgrade;if(nexus){this.world.upgradeNexus(nexus);this.showNexusPanel();return;}const shrine=e.target.closest('[data-shrine]')?.dataset.shrine;if(shrine){this.world.activateShrine(shrine);this.showMapPanel();return;}if(e.target.closest('[data-unlock-pad]')){this.world.unlockPad();this.showMapPanel();return;}if(e.target.closest('[data-bounty]')){this.world.acceptBounty();this.hideModal();return;}if(e.target.closest('[data-nexus-ability]')){this.world.activateNexusAbility();this.hideModal();return;}const bossReward=e.target.closest('[data-boss-reward]')?.dataset.bossReward;if(bossReward){this.hideModal();this.world.chooseBossReward(bossReward);return;}const legendary=e.target.closest('[data-legendary]')?.dataset.legendary;if(legendary){this.world.ascendSelectedLegendary(legendary);this.showRunPanel();return;}if(e.target.closest('[data-heatmap]')){this.world.toggleHeatmap();this.showBattleReport();return;}if(e.target.closest('[data-replay-seed]')){this.hideModal();this.game.restartSameSeed?.();return;}if(e.target.closest('[data-close-world]'))this.hideModal();});this.sync(true);}
 togglePanel(id){if(id==='nexus')this.showNexusPanel();else if(id==='map')this.showMapPanel();else this.showRunPanel();}
 sync(force=false){if(!this.root)return;const d=this.world.director,n=this.world.nexus,p=this.world.progression,m=this.world.map;const payload=`${this.game.state.wave}|${d.mutator?.id}|${d.objective?.id}|${d.bountyAccepted}|${p.artifacts.length}|${m.activeRoute}|${n.shield.toFixed(1)}|${n.abilityCooldown.toFixed(0)}|${this.world.seed}`;if(!force&&payload===this.last)return;this.last=payload;const body=this.root.querySelector('#worldHudBody');const mut=d.mutator?`<span class="world-chip danger">${esc(d.mutator.name)}</span>`:'';const obj=d.objective?`<span class="world-chip">${esc(d.objective.name)}</span>`:'';const bounty=d.bountyAccepted&&d.bounty?`<span class="world-chip bounty">PRIME · ${esc(d.bounty.name)}</span>`:'';body.innerHTML=`<div>${mut}${obj}${bounty}</div><small>Seed ${esc(this.world.seed)} · Route ${esc(m.activeRoute.toUpperCase())} · Nexus ${Math.ceil(n.shield)}/${Math.ceil(n.maxShield)} shield · Pulse ${n.abilityCooldown>0?Math.ceil(n.abilityCooldown)+'s':'PRÊT'}</small>`;}
 showModal(title,kicker,html){if(!this.modal)return;this.modal.classList.remove('hidden');this.modal.querySelector('#worldModalCard').innerHTML=`<button class="world-close" data-close-world aria-label="Fermer">×</button><small>${esc(kicker)}</small><h2>${esc(title)}</h2>${html}`;}
 hideModal(){this.modal?.classList.add('hidden');}
 showArtifactChoice(choices){if(!choices?.length)return;this.showModal('CHOISIS UN ARTEFACT','BOSS REWARD',`<div class="artifact-grid">${choices.slice(0,3).map(a=>`<button class="artifact-card" data-artifact="${esc(a.id)}"><b>${esc(a.icon)} ${esc(a.name)}</b><span class="positive">${esc(a.positive)}</span><span class="negative">${esc(a.negative)}</span></button>`).join('')}</div>`);this.game.audio?.playWorldCue?.('artifact');}
 showWaveChoice(choice){if(!choice?.options?.length)return;this.showModal('CHOISIS LE PROCHAIN DANGER','WAVE CHOICE',`<div class="wave-choice-grid">${choice.options.map(o=>`<button class="wave-choice-card" data-wave-choice="${esc(o.id)}"><b>${esc(o.name)}</b><span>${esc(o.description)}</span><em>${esc(o.risk)} · +${Math.round((o.reward-1)*100)} % récompense</em></button>`).join('')}</div>`);this.game.audio?.playWorldCue?.('wave-choice');}
 showBounty(bounty){if(!bounty)return;this.showModal(bounty.name,'CONTRAT OPTIONNEL',`<p>${esc(bounty.description)}</p><button class="world-primary" data-bounty>ACCEPTER · +${bounty.reward} OR</button>`);}
 showBossRewardChoice(rewards){if(!rewards?.length)return;this.showModal('CHOISIS TA RÉCOMPENSE','BOSS REWARD',`<div class="wave-choice-grid">${rewards.map(r=>`<button class="wave-choice-card" data-boss-reward="${esc(r.id)}"><b>${esc(r.name)}</b><span>${esc(r.hint)}</span><em>DÉCISION DE RUN</em></button>`).join('')}</div>`);}
 showNexusPanel(){const levels=this.world.progression.nexusLevels;this.showModal('NEXUS','FORTIFICATION & CAPACITÉ',`<div class="nexus-summary"><b>Shield ${Math.ceil(this.world.nexus.shield)} / ${Math.ceil(this.world.nexus.maxShield)}</b><span>Pulse défensif : ${this.world.nexus.abilityCooldown>0?Math.ceil(this.world.nexus.abilityCooldown)+' s':'PRÊT'}</span><button data-nexus-ability class="world-primary" ${this.world.nexus.abilityCooldown>0?'disabled':''}>DÉCLENCHER LE PULSE</button></div><div class="world-list">${NEXUS_UPGRADES.map(u=>{const level=levels[u.id]||0,cost=Math.round(u.cost*(1+level*.45));return `<button data-nexus-upgrade="${u.id}" ${level>=u.maxLevel?'disabled':''}><b>${esc(u.name)} · ${level}/${u.maxLevel}</b><span>${esc(u.description)}</span><em>${level>=u.maxLevel?'MAX':cost+' OR'}</em></button>`}).join('')}</div>`);}
 showMapPanel(){const map=this.world.map;this.showModal('BATTLEFIELD','SANCTUAIRES & EMPLACEMENTS',`<div class="world-list">${SHRINES.map(s=>{const active=map.shrines.get(s.id)?.active;return `<button data-shrine="${s.id}" ${active?'disabled':''}><b>${esc(s.name)}</b><span>${esc(s.element.toUpperCase())} · zone locale ${s.radius}</span><em>${active?'ACTIF':s.cost+' OR'}</em></button>`}).join('')}</div><button data-unlock-pad class="world-primary" ${map.lockedPads.size?'':'disabled'}>DÉBLOQUER UN SOCLE · ${map.lockedPads.size} RESTANT(S)</button><p class="world-note">Route active : <b>${esc(map.activeRoute.toUpperCase())}</b>${map.pendingRoute?` · prochaine : ${esc(map.pendingRoute.toUpperCase())}`:''}</p>`);}
 showRunPanel(){const p=this.world.progression,d=this.world.director,t=this.game.selectedTower,legendary=t?p.legendaryChoices(t):[];this.showModal('RUN STRATEGY','BUILD ACTUEL',`<div class="world-run-grid"><div><small>SEED</small><b>${esc(this.world.seed)}</b></div><div><small>ARTEFACTS</small><b>${p.artifacts.length}</b></div><div><small>PERFECT WAVES</small><b>${this.world.analytics.perfectWaves}</b></div><div><small>RÉACTIONS TERRAIN</small><b>${this.world.surfaces.stats.reactions}</b></div></div>${p.artifacts.length?`<div class="artifact-owned">${p.artifacts.map(a=>`<span>${esc(a.icon)} ${esc(a.name)}</span>`).join('')}</div>`:''}${d.bounty&&!d.bountyAccepted?`<button class="world-primary" data-bounty>ACCEPTER PRIME · ${esc(d.bounty.name)}</button>`:''}${t&&t.level>=3&&!t.legendary&&legendary.length?`<div class="world-list legendary-list">${legendary.map(l=>`<button data-legendary="${esc(l.id)}"><b>${esc(l.name)}</b><span>Ascension rare · silhouette et puissance uniques</span><em>${l.cost} OR</em></button>`).join('')}</div>`:''}`);}
 showBattleReport(){const r=this.world.analytics.report();this.showModal(this.game.state.victory?'VICTOIRE — BATTLEFIELD LEGACY':'BATTLE REPORT','RUN TERMINÉ',`<div class="battle-report"><div><small>SCORE</small><b>${r.score}</b></div><div><small>VAGUE</small><b>${r.wave}</b></div><div><small>KILLS</small><b>${r.kills}</b></div><div><small>BOSS</small><b>${r.bosses}</b></div><div><small>COMBOS</small><b>${r.combos}</b></div><div><small>SURFACES</small><b>${r.surfaces}</b></div><div><small>PERFECT</small><b>${r.perfectWaves}</b></div><div><small>OBJECTIFS</small><b>${r.objectives}</b></div><div><small>MVP</small><b>${esc(r.bestTower)}</b></div><div><small>ÉLÉMENT</small><b>${esc(r.bestElement)}</b></div><div><small>PLUS GROS HIT</small><b>${r.biggestHit}</b></div><div><small>COMBO DOMINANT</small><b>${esc(r.mostCombo)}</b></div><div><small>OR DÉPENSÉ</small><b>${r.goldSpent}</b></div><div><small>OR GAGNÉ</small><b>${r.goldEarned}</b></div><div><small>SEED</small><b>${esc(r.seed)}</b></div></div><div class="report-actions"><button class="world-primary" data-heatmap>HEATMAP · ${esc((this.world.heatmapMode||'off').toUpperCase())} → SUIVANTE</button><button class="world-secondary" data-replay-seed>REJOUER CETTE SEED</button></div>`);}
 destroy(){this.root?.remove();this.modal?.remove();}
}
