import * as THREE from 'three';
import { BUILD_PADS, DECOR, PATH } from '../config/map.js';
import { ELEMENTS } from '../config/elements.js';
import { toScene, material, emissiveMaterial, cylinder, box, crystal, torus, seeded, setShadow } from './drawing.js';

const TERRAIN_W=18.8,TERRAIN_D=11.2;
export class EnvironmentRenderer{
  constructor(game,scene){this.game=game;this.scene=scene;this.group=new THREE.Group();this.group.name='environment-3d';this.padViews=new Map();this.animated=[];scene.add(this.group);this.build();}
  build(){this.buildTerrain();this.buildRoad();this.buildPads();this.buildDecor();this.buildPortal(PATH[0],'entry');this.buildPortal(PATH.at(-1),'nexus');}
  buildTerrain(){
    const geometry=new THREE.PlaneGeometry(TERRAIN_W,TERRAIN_D,46,28);geometry.rotateX(-Math.PI/2);const pos=geometry.attributes.position;const colors=[];const rand=seeded(70421);const low=new THREE.Color('#3d7454'),high=new THREE.Color('#789d66'),earth=new THREE.Color('#596746');
    for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);const edge=Math.max(Math.abs(x)/9.4,Math.abs(z)/5.6);const ripple=Math.sin(x*1.13)*.025+Math.cos(z*1.47)*.021+(rand()-.5)*.032;const bowl=-Math.max(0,edge-.74)*.13;pos.setY(i,ripple+bowl-.035);let c=low.clone().lerp(high,THREE.MathUtils.clamp(.23+rand()*.5+ripple*2.8,0,1));if(rand()<.11)c.lerp(earth,.28);colors.push(c.r,c.g,c.b);}geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();const terrain=new THREE.Mesh(geometry,material('#fff',{vertexColors:true,roughness:1}));terrain.receiveShadow=true;terrain.name='terrain';this.group.add(terrain);
    const under=box(TERRAIN_W+.3,.48,TERRAIN_D+.3,'#293d31',{roughness:1});under.position.y=-.31;under.castShadow=false;this.group.add(under);
    const randTuft=seeded(5119),grassMat=material('#65935e',{roughness:1}),tuftGeo=new THREE.ConeGeometry(.035,.18,3),grass=new THREE.InstancedMesh(tuftGeo,grassMat,280),temp=new THREE.Object3D();
    for(let i=0;i<280;i++){temp.position.set((randTuft()-.5)*17.5,.08,(randTuft()-.5)*9.9);temp.rotation.y=randTuft()*Math.PI;const s=.65+randTuft()*.9;temp.scale.set(s,s,s);temp.updateMatrix();grass.setMatrixAt(i,temp.matrix);}grass.instanceMatrix.needsUpdate=true;this.group.add(grass);
  }
  buildRoad(){
    const road=new THREE.Group();road.name='road';const rand=seeded(8192);const contact=material('#34483b',{roughness:1}),borderMat=material('#66725a',{roughness:1}),roadMat=material('#a8946e',{roughness:.96}),tileMats=['#c9b285','#9f8b68','#b9a27a','#d0ba91'].map(c=>material(c,{roughness:1})),laneMat=emissiveMaterial('#f1dda9',.2,.68);
    for(let i=1;i<PATH.length;i++){const a=toScene(PATH[i-1].x,PATH[i-1].y),b=toScene(PATH[i].x,PATH[i].y);const dx=b.x-a.x,dz=b.z-a.z,length=Math.hypot(dx,dz),yaw=Math.atan2(dz,dx),center=a.clone().lerp(b,.5);
      const shadow=new THREE.Mesh(new THREE.BoxGeometry(length+.38,.03,1.16),contact);shadow.position.set(center.x,.012,center.z);shadow.rotation.y=-yaw;road.add(shadow);
      const border=new THREE.Mesh(new THREE.BoxGeometry(length+.26,.052,1.02),borderMat);border.position.set(center.x,.042,center.z);border.rotation.y=-yaw;border.receiveShadow=true;road.add(border);
      const strip=new THREE.Mesh(new THREE.BoxGeometry(length+.1,.072,.82),roadMat);strip.position.set(center.x,.078,center.z);strip.rotation.y=-yaw;strip.receiveShadow=true;road.add(strip);
      const tileCount=Math.max(2,Math.floor(length/.24));for(let j=0;j<tileCount;j++){const t=(j+.5)/tileCount,lateral=(rand()-.5)*.48,px=THREE.MathUtils.lerp(a.x,b.x,t)-Math.sin(yaw)*lateral,pz=THREE.MathUtils.lerp(a.z,b.z,t)+Math.cos(yaw)*lateral;const tile=new THREE.Mesh(new THREE.BoxGeometry(.1+rand()*.11,.023+rand()*.02,.13+rand()*.13),tileMats[j%tileMats.length]);tile.position.set(px,.123,pz);tile.rotation.y=-yaw+(rand()-.5)*.36;tile.receiveShadow=true;road.add(tile);}
      const markerCount=Math.max(1,Math.floor(length/.66));for(let j=0;j<markerCount;j++){const t=(j+.5)/markerCount,marker=new THREE.Mesh(new THREE.BoxGeometry(.16,.012,.05),laneMat);marker.position.set(THREE.MathUtils.lerp(a.x,b.x,t),.13,THREE.MathUtils.lerp(a.z,b.z,t));marker.rotation.y=-yaw;road.add(marker);}
    }this.group.add(road);
  }
  buildPads(){const stone=material('#7c877e',{roughness:.86}),inset=material('#36584a',{roughness:.72,metalness:.12});for(const pad of BUILD_PADS){const root=new THREE.Group();root.position.copy(toScene(pad.x,pad.y,.1));root.name=`pad-${pad.id}`;root.userData.pad=pad;const slab=new THREE.Mesh(new THREE.CylinderGeometry(.37,.45,.13,8),stone);slab.receiveShadow=slab.castShadow=true;root.add(slab);const core=new THREE.Mesh(new THREE.CylinderGeometry(.29,.31,.035,8),inset);core.position.y=.08;root.add(core);const ring=torus(.245,.014,'#8ff2c9',{intensity:.55,opacity:.34});ring.rotation.x=Math.PI/2;ring.position.y=.112;ring.material.depthWrite=false;root.add(ring);for(let i=0;i<8;i++){const rune=new THREE.Mesh(new THREE.BoxGeometry(.027,.012,.075),emissiveMaterial('#9ae7c7',.35,.5));const a=i/8*Math.PI*2;rune.position.set(Math.cos(a)*.22,.116,Math.sin(a)*.22);rune.rotation.y=-a;root.add(rune);}this.padViews.set(pad.id,{root,ring,core});this.group.add(root);}}
  buildDecor(){for(const item of DECOR){const root=this[item.type]?.(item)??this.rock(item);root.position.copy(toScene(item.x,item.y,.07));root.scale.setScalar(item.scale??1);root.rotation.y=item.variant*.78;setShadow(root,true,true);this.group.add(root);}}
  tree(item){const r=new THREE.Group(),trunk=cylinder(.08,.11,.72,'#4d3728',7,{roughness:1});trunk.position.y=.36;r.add(trunk);const pal=['#4d7d4b','#629052','#3f6b44'];for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.38-i*.035,1),material(pal[(item.variant+i)%pal.length],{roughness:1}));crown.position.set((i-1)*.14,.74+i*.19,(i%2?1:-1)*.06);crown.scale.y=1.2;r.add(crown);}return r;}
  bush(item){const r=new THREE.Group(),pal=['#557f4b','#6b9557','#436e43'];for(let i=0;i<4;i++){const c=new THREE.Mesh(new THREE.DodecahedronGeometry(.22+(i%2)*.045,0),material(pal[(item.variant+i)%pal.length],{roughness:1}));c.position.set((i-1.5)*.14,.2+(i%2)*.09,Math.sin(i*2)*.09);r.add(c);}return r;}
  rock(item){const r=new THREE.Group(),m=new THREE.Mesh(new THREE.DodecahedronGeometry(.34,0),material(item.variant%2?'#7a877f':'#69756d',{roughness:1}));m.position.y=.24;m.scale.set(1.15,.72,.9);r.add(m);return r;}
  crystal(item){const r=new THREE.Group(),colors=['#ad78ff','#71dcff','#d0a0ff'];for(let i=0;i<4;i++){const s=crystal(.11+i*.012,.55+i*.12,colors[(item.variant+i)%colors.length],{intensity:.7});s.position.set((i-1.5)*.13,.28+i*.05,(i%2?1:-1)*.08);s.rotation.z=(i-1.5)*.08;r.add(s);}return r;}
  ruin(item){const r=new THREE.Group();for(const side of[-1,1]){const c=cylinder(.095,.12,.7-(side>0?.18:0),'#788079',6,{roughness:1});c.position.set(side*.22,.35-(side>0?.09:0),0);r.add(c);}const cap=box(.58,.11,.18,'#707770',{roughness:1});cap.position.set(-.03,.73,0);cap.rotation.z=item.variant%2?.12:-.08;r.add(cap);return r;}
  buildPortal(point,kind){const root=new THREE.Group(),p=toScene(point.x,point.y,.08),isNexus=kind==='nexus',glow=isNexus?'#d69cff':'#7ff3bd',stone=isNexus?'#65556f':'#50695a';root.position.copy(p);root.name=`${kind}-portal`;const plinth=cylinder(.56,.7,.18,stone,8,{roughness:.9});plinth.position.y=.08;root.add(plinth);const halo=new THREE.Mesh(new THREE.RingGeometry(.5,.78,48),new THREE.MeshBasicMaterial({color:glow,transparent:true,opacity:.18,side:THREE.DoubleSide,depthWrite:false}));halo.rotation.x=-Math.PI/2;halo.position.y=.105;halo.name='portal-ground-halo';root.add(halo);
    if(isNexus){const core=crystal(.22,1.15,glow,{intensity:1.2});core.position.y=.72;core.name='portal-core';root.add(core);for(let i=0;i<3;i++){const ring=torus(.42+i*.12,.025,glow,{intensity:1.2,opacity:.78});ring.position.y=.72;ring.rotation.set(Math.PI/2,i*.65,i*.85);ring.name='portal-ring';root.add(ring);this.animated.push({type:'nexus-ring',object:ring,speed:.35+i*.18,phase:i});}const instability=new THREE.Group();instability.name='nexus-instability';for(let i=0;i<5;i++){const crack=box(.34+i*.045,.012,.025,'#ff9ad6',{emissive:'#c7428d',emissiveIntensity:1.4,roughness:.3});crack.position.set((i%2?1:-1)*(.08+i*.035),.19+i*.035,(i-2)*.085);crack.rotation.y=i*.73;instability.add(crack);}const unstableHalo=torus(.66,.018,'#ff7cbf',{intensity:1.45,opacity:.52});unstableHalo.rotation.x=Math.PI/2;unstableHalo.position.y=.16;unstableHalo.name='nexus-danger-halo';instability.add(unstableHalo);instability.visible=false;root.add(instability);}
    else{const ring=torus(.48,.075,glow,{intensity:1.25,opacity:.86});ring.position.y=.58;ring.name='portal-ring';root.add(ring);const inner=new THREE.Mesh(new THREE.CircleGeometry(.4,32),emissiveMaterial(glow,.8,.24));inner.position.y=.58;inner.position.z=.005;inner.material.side=THREE.DoubleSide;inner.name='portal-core';root.add(inner);this.animated.push({type:'entry-ring',object:ring,speed:.55,phase:0});}
    setShadow(root,true,true);this.group.add(root);this.animated.push({type:kind,object:root,speed:1,phase:isNexus?1.4:.2});}
  update(time,buildChoice,hoverPad,towers){const occupied=new Set(towers.map(t=>t.pad.id));for(const[id,view]of this.padViews){const hover=hoverPad?.id===id,selected=this.game.selectedPad?.id===id,used=occupied.has(id),active=Boolean(buildChoice)&&!used;view.ring.material.opacity=hover?.95:selected?.76:active?.58:.2;view.ring.material.emissiveIntensity=hover?2.1:selected?1.45:active?1.05:.38;view.ring.scale.setScalar(hover||selected?1.08+Math.sin(time*5)*.035:1);view.core.material.color.set(used?'#344039':active?'#3f705b':'#365347');}
    for(const item of this.animated){if(item.type==='nexus-ring'){item.object.rotation.y=time*item.speed+item.phase;item.object.rotation.z=time*item.speed*.72+item.phase;}else if(item.type==='entry-ring'){item.object.rotation.z=Math.sin(time*item.speed)*.08;}else{const core=item.object.getObjectByName('portal-core');if(core){const pulse=1+Math.sin(time*2.2+item.phase)*.06+(item.type==='nexus'?this.game.nexusPulse*.2:(this.game.spawnPulse+this.game.spawnCharge*.5)*.08);core.scale.setScalar(pulse);}const halo=item.object.getObjectByName('portal-ground-halo');if(halo){halo.material.opacity=.14+Math.sin(time*1.8+item.phase)*.035+(item.type==='nexus'?this.game.nexusPulse*.18:(this.game.spawnPulse+this.game.spawnCharge*.6)*.13);halo.scale.setScalar(1+Math.sin(time*1.35+item.phase)*.035);}if(item.type==='nexus'){const instability=item.object.getObjectByName('nexus-instability');if(instability){const lifeRatio=this.game.state.lives/Math.max(1,this.game.state.maxLives||30);instability.visible=lifeRatio<.42;if(instability.visible){const danger=1-lifeRatio;instability.rotation.y=Math.sin(time*.8)*.04;instability.scale.setScalar(.98+Math.sin(time*5)*.025*danger);const dangerHalo=instability.getObjectByName('nexus-danger-halo');if(dangerHalo){dangerHalo.rotation.z=time*.32;dangerHalo.material.opacity=.2+danger*.48+Math.sin(time*7)*.04;}}}}}}}
}
