import { WORLD,PATH,BUILD_PADS,DECOR } from '../config/map.js';
import { ELEMENTS } from '../config/elements.js';

export class Renderer{
  constructor(game,canvas){this.game=game;this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.time=0;this.dpr=Math.min(2,window.devicePixelRatio||1);}
  screenToWorld(clientX,clientY){const r=this.canvas.getBoundingClientRect();return{x:(clientX-r.left)/r.width*WORLD.width,y:(clientY-r.top)/r.height*WORLD.height};}
  render(dt){this.time+=dt;const c=this.ctx;c.save();c.clearRect(0,0,WORLD.width,WORLD.height);this.background(c);this.tiles(c);this.path(c);this.decor(c);this.pads(c);this.buildPreview(c);this.projectiles(c);this.towers(c);this.enemies(c);this.particles(c);this.portals(c);c.restore();}
  background(c){const g=c.createLinearGradient(0,0,0,WORLD.height);g.addColorStop(0,'#153e3a');g.addColorStop(.55,'#15362f');g.addColorStop(1,'#10251f');c.fillStyle=g;c.fillRect(0,0,WORLD.width,WORLD.height);const rg=c.createRadialGradient(1240,260,10,1240,260,420);rg.addColorStop(0,'#53407155');rg.addColorStop(1,'#0000');c.fillStyle=rg;c.fillRect(0,0,WORLD.width,WORLD.height);}
  tiles(c){c.lineWidth=1;for(let y=-20;y<WORLD.height+40;y+=46){for(let x=-40;x<WORLD.width+80;x+=78){const xx=x+((Math.floor(y/46)&1)*39);c.beginPath();c.moveTo(xx,y);c.lineTo(xx+39,y+23);c.lineTo(xx,y+46);c.lineTo(xx-39,y+23);c.closePath();c.fillStyle=((x+y)%156===0)?'#1a4237':'#183d34';c.fill();c.strokeStyle='#2d5a4930';c.stroke();}}}
  path(c){c.save();c.lineCap='round';c.lineJoin='round';c.beginPath();PATH.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle='#08110fcc';c.lineWidth=86;c.stroke();c.strokeStyle='#6b6550';c.lineWidth=70;c.stroke();c.strokeStyle='#9c9271';c.lineWidth=54;c.stroke();c.strokeStyle='#b7aa7d26';c.lineWidth=38;c.setLineDash([11,10]);c.stroke();c.setLineDash([]);c.restore();}
  pads(c){for(const pad of BUILD_PADS){const occupied=this.game.towers.some(t=>t.pad.id===pad.id);c.save();c.translate(pad.x,pad.y);c.scale(1,0.62);c.beginPath();c.arc(0,0,pad.r,0,Math.PI*2);let fill='#293d38';let stroke='#6b8d7a';if(this.game.buildChoice&&!occupied){fill='#174b3e';stroke='#69e3b1';}if(this.game.hoverPad?.id===pad.id&&this.game.buildChoice){fill=occupied?'#592e31':'#1d6951';stroke=occupied?'#ff777d':'#8dffd1';}c.fillStyle=fill;c.strokeStyle=stroke;c.lineWidth=2;c.fill();c.stroke();c.beginPath();c.arc(0,0,pad.r-7,0,Math.PI*2);c.strokeStyle='#d7dfbd22';c.stroke();c.restore();}}
  buildPreview(c){if(!this.game.buildChoice||!this.game.hoverWorld)return;const p=this.game.hoverWorld,pad=this.game.hoverPad,occupied=pad&&this.game.towers.some(t=>t.pad.id===pad.id),valid=!!pad&&!occupied;const color=valid?'#78f2be':'#ff7279';c.save();c.globalAlpha=.75;c.strokeStyle=color;c.fillStyle=color+'18';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,valid?this.game.getBuildRange():34,0,Math.PI*2);c.fill();c.stroke();c.beginPath();c.arc(p.x,p.y,16,0,Math.PI*2);c.fillStyle=color+'55';c.fill();c.restore();}
  decor(c){for(const d of DECOR){c.save();c.translate(d.x,d.y);c.scale(d.scale,d.scale);if(d.type==='tree'){c.fillStyle='#17231d';c.fillRect(-5,3,10,25);for(const [ox,oy,r,col] of [[0,-7,21,'#245d40'],[-14,1,16,'#2f774d'],[13,2,15,'#286947']]){c.beginPath();c.arc(ox,oy,r,0,Math.PI*2);c.fillStyle=col;c.fill();}}else if(d.type==='rock'){c.beginPath();c.moveTo(-22,12);c.lineTo(-13,-17);c.lineTo(11,-22);c.lineTo(24,7);c.lineTo(9,20);c.closePath();c.fillStyle='#53615b';c.fill();c.strokeStyle='#829089';c.stroke();}else if(d.type==='ruin'){c.fillStyle='#667069';c.fillRect(-20,-8,12,34);c.fillRect(8,-18,12,44);c.fillStyle='#7d867e';c.fillRect(-25,-11,22,6);c.fillRect(3,-21,22,6);}else{const pulse=.85+Math.sin(this.time*2+d.id)*.15;c.shadowBlur=18;c.shadowColor='#b97cff';c.fillStyle=`rgba(183,123,255,${pulse})`;c.beginPath();c.moveTo(0,-25);c.lineTo(12,-2);c.lineTo(4,20);c.lineTo(-10,8);c.lineTo(-13,-8);c.closePath();c.fill();c.shadowBlur=0;}c.restore();}}
  debugPath(c){if(!this.game.debug)return;c.save();c.strokeStyle='#ffda77';c.fillStyle='#ffda77';c.lineWidth=1;PATH.forEach((p,i)=>{c.beginPath();c.arc(p.x,p.y,5,0,Math.PI*2);c.fill();if(i){c.beginPath();c.moveTo(PATH[i-1].x,PATH[i-1].y);c.lineTo(p.x,p.y);c.stroke();}});c.restore();}
  portals(c){this.debugPath(c);this.portal(c,PATH[0].x+48,PATH[0].y,'#67f1bf','ENTRÉE');this.portal(c,PATH.at(-1).x-68,PATH.at(-1).y,'#c375ff','NEXUS');}
  portal(c,x,y,color,label){c.save();c.translate(x,y);const p=.6+.4*Math.sin(this.time*3);c.shadowBlur=28;c.shadowColor=color;c.strokeStyle=color;c.lineWidth=6;c.beginPath();c.ellipse(0,-18,24,40,0,0,Math.PI*2);c.stroke();c.globalAlpha=.24+p*.18;c.fillStyle=color;c.beginPath();c.ellipse(0,-18,18,32,0,0,Math.PI*2);c.fill();c.globalAlpha=1;c.shadowBlur=0;c.font='700 10px system-ui';c.textAlign='center';c.fillStyle='#e7fff7';c.fillText(label,0,40);c.restore();}
  towers(c){for(const t of this.game.towers){const el=ELEMENTS[t.def.element],selected=this.game.selectedTower===t;if(selected||this.game.debug){c.save();c.strokeStyle=el.color+'88';c.fillStyle=el.color+'10';c.lineWidth=2;c.beginPath();c.arc(t.x,t.y,t.stats.range,0,Math.PI*2);c.fill();c.stroke();c.restore();}c.save();c.translate(t.x,t.y);c.scale(1,.72);c.fillStyle='#26332f';c.strokeStyle='#81968d';c.lineWidth=2;c.beginPath();c.arc(0,12,24,0,Math.PI*2);c.fill();c.stroke();c.scale(1,1/.72);c.shadowBlur=t.flash?30:12;c.shadowColor=el.color;c.rotate(t.angle);c.fillStyle=el.color;c.strokeStyle='#eaffff88';c.lineWidth=2;if(t.def.projectile==='rock'){c.fillRect(-7,-18,24,20);c.strokeRect(-7,-18,24,20);}else if(t.def.projectile==='bolt'){c.beginPath();c.moveTo(-9,15);c.lineTo(0,-27);c.lineTo(9,15);c.closePath();c.fill();c.stroke();}else if(t.def.projectile==='prism'||t.def.projectile==='arc'){c.beginPath();c.moveTo(0,-31);c.lineTo(14,-4);c.lineTo(0,14);c.lineTo(-14,-4);c.closePath();c.fill();c.stroke();}else{c.beginPath();c.arc(0,-8,13+3*t.level,0,Math.PI*2);c.fill();c.stroke();}c.shadowBlur=0;c.rotate(-t.angle);c.fillStyle='#ecfff8';c.font='800 9px system-ui';c.textAlign='center';c.fillText(String(t.level),0,25);c.restore();}}
  enemies(c){for(const e of this.game.enemies){c.save();c.translate(e.x,e.y);const bob=Math.sin(this.time*6+e.distance*.03)*2;c.translate(0,bob);if(e.def.boss){c.shadowBlur=22;c.shadowColor=e.def.color;}if(e.shield>0){c.strokeStyle='#8de8ffbb';c.lineWidth=2;c.beginPath();c.arc(0,-6,e.def.size+8,0,Math.PI*2);c.stroke();}c.fillStyle=e.def.color;c.strokeStyle='#15211f';c.lineWidth=2;if(e.def.id==='swift'){c.beginPath();c.moveTo(15,0);c.lineTo(-10,-10);c.lineTo(-5,0);c.lineTo(-10,10);c.closePath();}else if(e.def.id==='tank'){c.beginPath();c.rect(-e.def.size,-e.def.size,e.def.size*2,e.def.size*2);}else{c.beginPath();c.arc(0,0,e.def.size,0,Math.PI*2);}c.fill();c.stroke();c.shadowBlur=0;const w=e.def.boss?54:34;c.fillStyle='#07110f';c.fillRect(-w/2,-e.def.size-15,w,5);c.fillStyle=e.hp/e.maxHp>.5?'#6fe37f':e.hp/e.maxHp>.25?'#f2c665':'#ff656d';c.fillRect(-w/2,-e.def.size-15,w*(e.hp/e.maxHp),5);let i=0;for(const [name] of e.effects){if(i>3)break;c.fillStyle=name==='burn'?'#ff7044':name==='poison'?'#70d967':name==='slow'||name==='freeze'?'#72dfff':name==='stun'?'#ffd970':'#c38aff';c.fillRect(-14+i*8,-e.def.size-23,6,6);i++;}c.restore();}}
  projectiles(c){for(const p of this.game.projectiles){c.save();c.translate(p.x,p.y);const col=ELEMENTS[p.element].color;c.shadowBlur=14;c.shadowColor=col;c.fillStyle=col;if(p.kind==='shard'||p.kind==='prism'){c.rotate(this.time*8);c.fillRect(-3,-9,6,18);}else if(p.kind==='rock'){c.beginPath();c.arc(0,0,7,0,Math.PI*2);c.fill();}else{c.beginPath();c.arc(0,0,p.kind==='meteor'?9:5,0,Math.PI*2);c.fill();}c.restore();}}
  particles(c){for(const p of this.game.particles.items){c.save();c.globalAlpha=Math.max(0,p.life/p.max);c.fillStyle=p.color;c.shadowBlur=8;c.shadowColor=p.color;c.beginPath();c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill();c.restore();}for(const b of this.game.particles.beams){c.save();c.globalAlpha=b.life/b.max;c.strokeStyle=b.color;c.shadowBlur=14;c.shadowColor=b.color;c.lineWidth=3;c.beginPath();b.points.forEach((p,i)=>{const jitter=i&&i<b.points.length-1?(Math.random()-.5)*5:0;i?c.lineTo(p.x+jitter,p.y-jitter):c.moveTo(p.x,p.y);});c.stroke();c.restore();}}
}
