import * as THREE from 'three';
import { ELEMENTS } from '../config/elements.js';
import { TOWER_BY_ID, getSpecialization } from '../config/towers.js';
import { PAD_BASELINE_RANGE } from '../config/map.js';
import { SCENE_SCALE,toScene,material,emissiveMaterial,cylinder,box,sphere,crystal,torus,markInteractive,disposeObject } from './drawing.js';

export class TowerRenderer{
  constructor(game,scene){this.game=game;this.scene=scene;this.group=new THREE.Group();this.group.name='towers-3d';scene.add(this.group);this.views=new Map();this.range=null;this.preview=null;this.previewKey='';this._scenePos=new THREE.Vector3();}
  sync(time){const live=new Set(this.game.towers);for(const[tower,view]of this.views){if(live.has(tower))continue;this.group.remove(view);disposeObject(view);this.views.delete(tower);}for(const tower of this.game.towers){let view=this.views.get(tower);if(!view||view.userData.level!==tower.level||view.userData.specialization!==tower.specialization){if(view){this.group.remove(view);disposeObject(view);}view=this.createTower(tower.def,tower.level,false,true,tower.specialization);view.userData.level=tower.level;view.userData.specialization=tower.specialization;markInteractive(view,'tower',tower);this.group.add(view);this.views.set(tower,view);}this.updateTower(view,tower,time);}this.syncRange();this.syncPreview(time);}
  createTower(def,level=1,ghost=false,valid=true,specialization=null){const el=ELEMENTS[def.element],root=new THREE.Group();root.name=`tower-${def.id}`;root.userData.level=level;const baseColor=ghost?(valid?'#4c725f':'#7a5148'):'#4d5953';const base=cylinder(.30+level*.026,.38+level*.026,.16,baseColor,8,{roughness:.82,metalness:.08});base.position.y=.08;root.add(base);const inset=cylinder(.245,.27,.055,'#27332e',8,{roughness:.65,metalness:.16});inset.position.y=.185;root.add(inset);const rune=torus(.205,.016,valid?el.color:'#ff7066',{intensity:ghost?.8:.45,opacity:ghost?.72:.46});rune.rotation.x=Math.PI/2;rune.position.y=.225;root.add(rune);const head=new THREE.Group();head.name='head';head.position.y=.22;root.add(head);this[def.id.replaceAll('-','_')]?.(head,el,level);
    if(level>=2){for(const side of[-1,1]){const shard=crystal(.04,.25+level*.04,el.color,{intensity:.65});shard.position.set(side*.25,.16,.02);shard.rotation.z=side*.32;root.add(shard);}}
    if(level>=3){const crown=torus(.31,.012,el.light,{intensity:1.05,opacity:.75});crown.rotation.x=Math.PI/2;crown.position.y=.34;crown.name='level-crown';root.add(crown);}
    const spec=getSpecialization(def.element,specialization);if(spec){const aggressive=(spec.mods.damage||1)>1.1||spec.mods.pure||spec.mods.burn||spec.mods.poison;const specRoot=new THREE.Group();specRoot.name='specialization-crown';for(let i=0;i<(aggressive?3:4);i++){const a=i/(aggressive?3:4)*Math.PI*2;const shard=crystal(aggressive?.055:.045,aggressive?.34:.26,aggressive?el.light:el.color,{intensity:aggressive?1.25:.85});shard.position.set(Math.cos(a)*(aggressive?.37:.33),.46+Math.sin(a*2)*.035,Math.sin(a)*(aggressive?.37:.33));shard.rotation.z=Math.cos(a)*.38;specRoot.add(shard);}const halo=torus(aggressive?.39:.35,.011,aggressive?el.light:el.color,{intensity:1.35,opacity:.62});halo.rotation.x=Math.PI/2;halo.position.y=.49;halo.name='specialization-halo';specRoot.add(halo);root.add(specRoot);root.userData.specialization=specialization;}
    if(ghost)this.setOpacity(root,.62);return root;}
  ember_spire(root,el,level){const spire=new THREE.Mesh(new THREE.ConeGeometry(.18,.78+level*.08,5),material('#342823',{roughness:.72}));spire.position.y=.41;root.add(spire);const flame=crystal(.11+level*.012,.34,'#ff7a37',{intensity:1.8});flame.position.y=.93+level*.07;flame.name='pulse-core';root.add(flame);}
  magma_forge(root,el,level){const bowl=cylinder(.27,.2,.34,'#3b302a',10,{roughness:.78,metalness:.12});bowl.position.y=.3;root.add(bowl);const lava=cylinder(.21,.21,.035,'#ff7136',16,{emissive:'#ff4d1f',emissiveIntensity:2.2,roughness:.2});lava.position.y=.49;lava.name='pulse-core';root.add(lava);for(const side of[-1,1]){const vent=box(.12,.18,.28,'#60473b',{roughness:.8});vent.position.set(side*.31,.25,0);vent.rotation.z=side*.2;root.add(vent);}}
  frost_obelisk(root,el,level){const pillar=crystal(.18,.88+level*.08,'#74dcf1',{intensity:.75});pillar.position.y=.48;root.add(pillar);const core=new THREE.Mesh(new THREE.OctahedronGeometry(.15+level*.012),emissiveMaterial(el.light,1.15,.88));core.position.y=.96+level*.06;core.name='spin-core';root.add(core);}
  cryo_prism(root,el,level){const stem=cylinder(.09,.14,.5,'#3c626c',7,{roughness:.72});stem.position.y=.29;root.add(stem);const prism=new THREE.Mesh(new THREE.OctahedronGeometry(.27+level*.02),emissiveMaterial('#8eefff',1.15,.92));prism.position.y=.74;prism.scale.y=1.35;prism.name='spin-core';root.add(prism);const ring=torus(.34,.02,'#dffcff',{intensity:1.15,opacity:.72});ring.position.y=.74;ring.rotation.x=Math.PI/2;ring.name='orbit-ring';root.add(ring);}
  spark_coil(root,el,level){const mast=cylinder(.075,.12,.72,'#3a4d61',8,{roughness:.56,metalness:.45});mast.position.y=.38;root.add(mast);for(let i=0;i<3+level;i++){const ring=torus(.19+i*.012,.022,'#79a8d0',{emissive:false,roughness:.45,metalness:.55});ring.rotation.x=Math.PI/2;ring.position.y=.3+i*.13;root.add(ring);}const orb=sphere(.13,el.light,16,{emissive:el.color,emissiveIntensity:2.3,roughness:.2});orb.position.y=.88;orb.name='pulse-core';root.add(orb);}
  tempest_pylon(root,el,level){const hub=cylinder(.15,.2,.42,'#33475e',7,{roughness:.62,metalness:.32});hub.position.y=.25;root.add(hub);for(let i=0;i<3;i++){const a=i/3*Math.PI*2,prong=crystal(.07,.65+level*.05,'#72afea',{intensity:.55});prong.position.set(Math.cos(a)*.21,.56,Math.sin(a)*.21);prong.rotation.z=Math.cos(a)*.18;prong.rotation.x=Math.sin(a)*.18;root.add(prong);}const orb=sphere(.15,'#f1fbff',16,{emissive:el.color,emissiveIntensity:2.4,roughness:.12});orb.position.y=.88;orb.name='pulse-core';root.add(orb);}
  thorn_nest(root,el,level){const heart=sphere(.22,'#3c5a3b',12,{roughness:.95});heart.position.y=.36;root.add(heart);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,thorn=new THREE.Mesh(new THREE.ConeGeometry(.045,.43+level*.03,5),material('#6e8248',{roughness:1}));thorn.position.set(Math.cos(a)*.24,.37,Math.sin(a)*.24);thorn.rotation.z=Math.cos(a)*1.05;thorn.rotation.x=-Math.sin(a)*1.05;root.add(thorn);}const seed=sphere(.11,el.light,12,{emissive:el.color,emissiveIntensity:1.1,roughness:.5});seed.position.y=.62;seed.name='pulse-core';root.add(seed);}
  bloom_sanctum(root,el,level){const trunk=cylinder(.08,.14,.66,'#56452f',7,{roughness:1});trunk.position.y=.34;root.add(trunk);for(let i=0;i<5;i++){const a=i/5*Math.PI*2,petal=sphere(.15+level*.008,'#65a55b',12,{roughness:.85});petal.position.set(Math.cos(a)*.21,.7+Math.sin(a*2)*.04,Math.sin(a)*.21);petal.scale.set(1.25,.72,.85);root.add(petal);}const bloom=sphere(.13,'#e8fdb9',16,{emissive:el.color,emissiveIntensity:1.25,roughness:.35});bloom.position.y=.75;bloom.name='spin-core';root.add(bloom);}
  stone_bastion(root,el,level){const tower=box(.47,.48+level*.05,.47,'#626b65',{roughness:.94});tower.position.y=.28;root.add(tower);for(let i=0;i<4;i++){const a=i/4*Math.PI*2,merlon=box(.14,.18,.14,'#777e76',{roughness:.94});merlon.position.set(Math.cos(a)*.19,.62+level*.03,Math.sin(a)*.19);root.add(merlon);}const core=crystal(.08,.27,el.color,{intensity:.55});core.position.y=.72;core.name='pulse-core';root.add(core);}
  seismic_hammer(root,el,level){const support=cylinder(.12,.17,.62,'#565d59',8,{roughness:.85,metalness:.16});support.position.y=.34;root.add(support);const pivot=sphere(.13,'#926b46',12,{roughness:.75,metalness:.22});pivot.position.y=.67;root.add(pivot);const handle=box(.1,.1,.68,'#60462e',{roughness:.95});handle.position.set(0,.68,.24);handle.name='recoil-part';root.add(handle);const hammer=box(.5+level*.05,.24,.26,'#807d72',{roughness:.8,metalness:.18});hammer.position.set(0,.68,.56);hammer.name='recoil-part';root.add(hammer);}
  arcane_eye(root,el,level){const stem=cylinder(.07,.13,.58,'#4c3a59',7,{roughness:.66,metalness:.18});stem.position.y=.3;root.add(stem);const ring=torus(.31+level*.015,.035,'#bc84f7',{intensity:1.25,opacity:.88});ring.position.y=.73;ring.name='spin-core';root.add(ring);const eye=sphere(.14,'#f3e5ff',16,{emissive:el.color,emissiveIntensity:2,roughness:.2});eye.position.y=.73;eye.scale.z=.5;eye.name='pulse-core';root.add(eye);}
  rift_weaver(root,el,level){for(const side of[-1,1]){const pillar=crystal(.105,.82+level*.06,'#754f96',{intensity:.42});pillar.position.set(side*.2,.43,0);pillar.rotation.z=side*.08;root.add(pillar);}const rift=new THREE.Mesh(new THREE.OctahedronGeometry(.22+level*.015),emissiveMaterial('#dcb1ff',1.8,.82));rift.position.y=.76;rift.scale.y=1.55;rift.name='spin-core';root.add(rift);const ring=torus(.36,.018,el.color,{intensity:1.4,opacity:.72});ring.position.y=.76;ring.rotation.x=Math.PI/2;ring.name='orbit-ring';root.add(ring);}
  updateTower(view,tower,time){toScene(tower.x,tower.y,.14,this._scenePos);view.position.copy(this._scenePos);const buildScale=1+tower.buildFx*.18;view.scale.setScalar(buildScale);const head=view.getObjectByName('head');if(head){head.rotation.y=Math.PI/2-tower.angle;head.position.z=-tower.recoil*.04;}const spin=view.getObjectByName('spin-core');if(spin)spin.rotation.y=time*1.35+tower.phase;const orbit=view.getObjectByName('orbit-ring');if(orbit)orbit.rotation.z=time*.9+tower.phase;const pulse=view.getObjectByName('pulse-core');if(pulse){const value=1+Math.sin(time*4+tower.phase)*.055+tower.flash*.12;pulse.scale.multiplyScalar(1/(pulse.userData.lastScale||1));pulse.scale.multiplyScalar(value);pulse.userData.lastScale=value;}const crown=view.getObjectByName('level-crown');if(crown)crown.rotation.z=time*.55;const specCrown=view.getObjectByName('specialization-crown');if(specCrown)specCrown.rotation.y=time*.42+tower.phase*.2;const specHalo=view.getObjectByName('specialization-halo');if(specHalo)specHalo.rotation.z=-time*.66;}
  syncRange(){const tower=this.game.selectedTower,buildDef=TOWER_BY_ID[this.game.buildChoice],pad=tower?{x:tower.x,y:tower.y}:(buildDef&&this.game.hoverPad)||this.game.selectedPad;if(!pad){if(this.range)this.range.visible=false;return;}const def=tower?.def??buildDef,range=tower?.stats.range??def?.range??PAD_BASELINE_RANGE,element=def?.element??'arcane',occupied=!tower&&this.game.selectedPad&&this.game.towers.some(t=>t.pad.id===this.game.selectedPad.id),valid=!occupied,r=range*SCENE_SCALE,key=`${element}-${r.toFixed(3)}-${valid}`;if(!this.range||this.range.userData.key!==key){if(this.range){this.scene.remove(this.range);disposeObject(this.range);}const el=ELEMENTS[element],color=valid?el.color:'#ff746b',light=valid?el.light:'#ffb2ad',root=new THREE.Group(),disk=new THREE.Mesh(new THREE.CircleGeometry(r,96),new THREE.MeshBasicMaterial({color,transparent:true,opacity:tower?.052:.07,depthWrite:false,side:THREE.DoubleSide}));disk.rotation.x=-Math.PI/2;root.add(disk);const ring=new THREE.Mesh(new THREE.RingGeometry(Math.max(.01,r-.018),r+.018,128),new THREE.MeshBasicMaterial({color:light,transparent:true,opacity:.68,depthWrite:false,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.008;root.add(ring);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,tick=new THREE.Mesh(new THREE.BoxGeometry(.012,.004,.075),new THREE.MeshBasicMaterial({color:light,transparent:true,opacity:.72,depthWrite:false}));tick.position.set(Math.cos(a)*r,.012,Math.sin(a)*r);tick.rotation.y=-a;root.add(tick);}root.userData.key=key;this.scene.add(root);this.range=root;}this.range.visible=true;toScene(pad.x,pad.y,.122,this._scenePos);this.range.position.copy(this._scenePos);}
  syncPreview(time){const def=TOWER_BY_ID[this.game.buildChoice],point=this.game.hoverPad??this.game.hoverWorld;if(!def||!point){if(this.preview)this.preview.visible=false;return;}const occupied=this.game.hoverPad&&this.game.towers.some(t=>t.pad.id===this.game.hoverPad.id),valid=Boolean(this.game.hoverPad)&&!occupied,key=`${def.id}-${valid}`;if(!this.preview||this.previewKey!==key){if(this.preview){this.scene.remove(this.preview);disposeObject(this.preview);}this.preview=this.createTower(def,1,true,valid);this.previewKey=key;this.scene.add(this.preview);}this.preview.visible=true;toScene(point.x,point.y,.15,this._scenePos);this.preview.position.copy(this._scenePos);this.preview.rotation.y=Math.sin(time*1.8)*.04;}
  setOpacity(root,opacity){root.traverse(n=>{if(!n.isMesh)return;n.material=n.material.clone();n.material.transparent=true;n.material.opacity*=opacity;n.material.depthWrite=false;});}
}
