import * as THREE from 'three';
import { ELEMENTS } from '../config/elements.js';
import { toScene, emissiveMaterial, disposeObject } from './drawing.js';
const SOFT_TYPES=new Set(['smoke','dust','leaf']);
export class VfxRenderer{
  constructor(game,scene,camera){this.game=game;this.scene=scene;this.camera=camera;this.group=new THREE.Group();this.group.name='vfx-3d';scene.add(this.group);this.projectiles=new Map();this.rings=new Map();this.beams=new Map();this.texts=new Map();this.burstViews=new Map();this.burstPools=new Map();this.decalViews=new Map();this.decalPool=[];this._tempColor=new THREE.Color();this._tempPoint=new THREE.Vector3();this.buildParticleClouds();}
  makeCloud(size,opacity,blending){const count=this.game.particles.maxParticles,geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(count*3),3));geometry.setAttribute('color',new THREE.BufferAttribute(new Float32Array(count*3),3));const mat=new THREE.PointsMaterial({size,sizeAttenuation:true,vertexColors:true,transparent:true,opacity,depthWrite:false,blending});const cloud=new THREE.Points(geometry,mat);cloud.frustumCulled=false;this.group.add(cloud);return cloud;}
  buildParticleClouds(){this.sparkCloud=this.makeCloud(.075,.95,THREE.AdditiveBlending);this.softCloud=this.makeCloud(.13,.52,THREE.NormalBlending);}
  sync(time){this.syncProjectiles(time);this.syncParticles();this.syncRings();this.syncBeams();this.syncBursts();this.syncDecals();this.syncTexts();}
  syncProjectiles(time){const live=new Set(this.game.projectiles);for(const[p,v]of this.projectiles){if(live.has(p))continue;this.group.remove(v);disposeObject(v);this.projectiles.delete(p);}for(const p of this.game.projectiles){let view=this.projectiles.get(p);if(!view){view=this.createProjectile(p);this.group.add(view);this.projectiles.set(p,view);}const h=p.kind==='meteor'?.92:p.kind==='rock'?.48:.62;toScene(p.x,p.y,h,this._tempPoint);view.position.copy(this._tempPoint);view.rotation.y=p.spin;view.rotation.z=p.spin*.45;const history=view.userData.history;for(let i=history.length-1;i>0;i--)history[i].copy(history[i-1]);history[0].copy(this._tempPoint);const rel=view.userData.relative;for(let i=0;i<history.length;i++)rel[i].copy(history[i]).sub(this._tempPoint);const trail=view.getObjectByName('trail');trail.geometry.setFromPoints(rel);trail.material.opacity=p.kind==='meteor'?.78:.62;const core=view.getObjectByName('projectile-core');if(core)core.scale.setScalar(1+Math.sin(time*12+p.spin)*.08);if(time-view.userData.lastParticle>(p.kind==='meteor'?.055:.09)){view.userData.lastParticle=time;if(p.kind==='meteor'){this.game.particles.spawn(p.x,p.y,{color:'#77675c',count:1,power:7,type:'smoke',r:5.5,life:.55,drag:.98,upBias:7});this.game.particles.spawn(p.x,p.y,{color:'#ff9a47',count:1,power:16,type:'spark',r:2,life:.22,glow:8});}else if(p.element==='ice')this.game.particles.spawn(p.x,p.y,{color:'#d8fbff',count:1,power:8,type:'shard',r:1.8,life:.22,glow:5});}}
  }
  createProjectile(p){const root=new THREE.Group(),el=ELEMENTS[p.element];let geometry;if(p.kind==='shard'||p.kind==='prism')geometry=new THREE.OctahedronGeometry(p.kind==='prism'?.14:.105);else if(p.kind==='rock')geometry=new THREE.DodecahedronGeometry(.14,0);else if(p.kind==='meteor')geometry=new THREE.IcosahedronGeometry(.2,1);else if(p.kind==='thorn'||p.kind==='seed')geometry=new THREE.ConeGeometry(.075,.28,5);else if(p.kind==='arc')geometry=new THREE.OctahedronGeometry(.09,0);else geometry=new THREE.IcosahedronGeometry(.105,1);const core=new THREE.Mesh(geometry,emissiveMaterial(el.color,p.kind==='meteor'?2.7:1.9));core.name='projectile-core';if(p.kind==='arc')core.scale.set(.7,.7,1.6);root.add(core);const trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:p.kind==='meteor'?'#ffb85c':el.light,transparent:true,opacity:.66,blending:THREE.AdditiveBlending,depthWrite:false}));trail.name='trail';root.add(trail);root.userData.history=Array.from({length:p.kind==='meteor'?11:p.kind==='arc'?8:5},()=>new THREE.Vector3());root.userData.relative=root.userData.history.map(()=>new THREE.Vector3());root.userData.lastParticle=-999;return root;}
  syncParticles(){const spark=[],soft=[];for(const p of this.game.particles.items)(SOFT_TYPES.has(p.type)?soft:spark).push(p);this.writeCloud(this.sparkCloud,spark,false);this.writeCloud(this.softCloud,soft,true);}
  writeCloud(cloud,items,soft){const positions=cloud.geometry.attributes.position,colors=cloud.geometry.attributes.color,count=Math.min(items.length,positions.count);for(let i=0;i<count;i++){const p=items[i],progress=1-p.life/Math.max(.001,p.max),base=p.height??(soft?.22:.15),lift=soft?base+progress*.52:base+Math.sin(progress*Math.PI)*.3;toScene(p.x,p.y,lift,this._tempPoint);positions.setXYZ(i,this._tempPoint.x,this._tempPoint.y,this._tempPoint.z);this._tempColor.set(p.color||'#fff');const fade=THREE.MathUtils.clamp(p.life/Math.max(.001,p.max),0,1),mul=soft?fade*.72:fade;colors.setXYZ(i,this._tempColor.r*mul,this._tempColor.g*mul,this._tempColor.b*mul);}positions.needsUpdate=true;colors.needsUpdate=true;cloud.geometry.setDrawRange(0,count);}
  syncRings(){const live=new Set(this.game.particles.rings);for(const[r,v]of this.rings){if(live.has(r))continue;this.group.remove(v);disposeObject(v);this.rings.delete(r);}for(const r of this.game.particles.rings){let v=this.rings.get(r);if(!v){v=new THREE.Mesh(new THREE.RingGeometry(.97,1.03,48),new THREE.MeshBasicMaterial({color:r.color,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));v.rotation.x=-Math.PI/2;this.group.add(v);this.rings.set(r,v);}const progress=1-r.life/r.max,radius=THREE.MathUtils.lerp(r.from,r.to,progress)*.01;toScene(r.x,r.y,.14,this._tempPoint);v.position.copy(this._tempPoint);v.scale.set(radius,radius*(r.aspect||1),radius);v.material.opacity=Math.max(0,r.life/r.max)*.72;}}
  syncBeams(){const live=new Set(this.game.particles.beams);for(const[b,v]of this.beams){if(live.has(b))continue;this.group.remove(v);disposeObject(v);this.beams.delete(b);}for(const b of this.game.particles.beams){let v=this.beams.get(b);if(!v){v=new THREE.Group();const halo=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:b.color,transparent:true,opacity:.28,blending:THREE.AdditiveBlending,depthWrite:false})),core=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:'#f4ffff',transparent:true,opacity:.95,blending:THREE.AdditiveBlending,depthWrite:false}));halo.name='beam-halo';core.name='beam-core';v.add(halo,core);v.userData.points=[];this.group.add(v);this.beams.set(b,v);}const points=v.userData.points;while(points.length<b.points.length)points.push(new THREE.Vector3());points.length=b.points.length;for(let i=0;i<b.points.length;i++){const p=b.points[i];toScene(p.x,p.y,i===0?.72:.5,points[i]);}v.getObjectByName('beam-halo').geometry.setFromPoints(points);v.getObjectByName('beam-core').geometry.setFromPoints(points);const fade=Math.max(0,b.life/b.max);v.getObjectByName('beam-halo').material.opacity=fade*.36;v.getObjectByName('beam-core').material.opacity=fade;}}
  syncBursts(){const live=new Set(this.game.particles.bursts);for(const[b,v]of this.burstViews){if(live.has(b))continue;this.releaseBurstView(b.kind,v);this.burstViews.delete(b);}for(const b of this.game.particles.bursts){let v=this.burstViews.get(b);if(!v){v=this.acquireBurstView(b.kind);this.burstViews.set(b,v);}this.updateBurstView(v,b);}}
  acquireBurstView(kind){const pool=this.burstPools.get(kind)||[];this.burstPools.set(kind,pool);const pooled=pool.pop();if(pooled){pooled.visible=true;this.group.add(pooled);return pooled;}const root=new THREE.Group();root.userData.kind=kind;const flash=new THREE.Mesh(new THREE.IcosahedronGeometry(.26,1),new THREE.MeshBasicMaterial({color:'#fff',transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));flash.name='burst-flash';root.add(flash);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.42,2),new THREE.MeshBasicMaterial({color:'#ff8b3d',transparent:true,opacity:.65,blending:THREE.AdditiveBlending,depthWrite:false}));core.name='burst-core';root.add(core);const shock=new THREE.Mesh(new THREE.RingGeometry(.9,1.05,64),new THREE.MeshBasicMaterial({color:'#ffd28a',transparent:true,opacity:.65,blending:THREE.AdditiveBlending,side:THREE.DoubleSide,depthWrite:false}));shock.name='burst-shock';shock.rotation.x=-Math.PI/2;root.add(shock);this.group.add(root);return root;}
  releaseBurstView(kind,view){this.group.remove(view);view.visible=false;const pool=this.burstPools.get(kind)||[];this.burstPools.set(kind,pool);if(pool.length<16)pool.push(view);else disposeObject(view);}
  updateBurstView(view,b){const progress=1-b.life/b.max,fade=Math.max(0,b.life/b.max),power=b.power||1;toScene(b.x,b.y,b.kind==='spawn'?.32:.34,this._tempPoint);view.position.copy(this._tempPoint);const flash=view.getObjectByName('burst-flash'),core=view.getObjectByName('burst-core'),shock=view.getObjectByName('burst-shock');flash.material.color.set(b.kind==='explosion'?'#fff2c8':b.color);core.material.color.set(b.color);shock.material.color.set(b.kind==='explosion'?'#ffd18a':b.color);flash.scale.setScalar(power*(.35+Math.sin(Math.min(1,progress*2)*Math.PI)*.72));flash.material.opacity=fade*(b.kind==='shock'?.28:.78);core.scale.setScalar(power*(.18+progress*(b.kind==='explosion'?.95:.55)));core.material.opacity=fade*(b.kind==='explosion'?.58:b.kind==='spawn'?.28:.4);shock.scale.setScalar(power*(.18+progress*(b.kind==='explosion'?1.45:.95)));shock.material.opacity=fade*(b.kind==='explosion'||b.kind==='shock'?.58:.34);}
  syncDecals(){const live=new Set(this.game.particles.decals);for(const[d,v]of this.decalViews){if(live.has(d))continue;this.group.remove(v);v.visible=false;if(this.decalPool.length<32)this.decalPool.push(v);else disposeObject(v);this.decalViews.delete(d);}for(const d of this.game.particles.decals){let v=this.decalViews.get(d);if(!v){v=this.decalPool.pop()||new THREE.Mesh(new THREE.RingGeometry(.45,1,20),new THREE.MeshBasicMaterial({color:d.color,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}));v.visible=true;this.group.add(v);this.decalViews.set(d,v);}v.material.color.set(d.color);v.material.opacity=d.opacity*Math.max(0,d.life/d.max);v.rotation.x=-Math.PI/2;v.rotation.z=d.rot;toScene(d.x,d.y,.118,this._tempPoint);v.position.copy(this._tempPoint);v.scale.setScalar(d.scale*.34);}}
  syncTexts(){const live=new Set(this.game.particles.texts);for(const[t,v]of this.texts){if(live.has(t))continue;this.group.remove(v);v.material.map?.dispose();v.material.dispose();this.texts.delete(t);}for(const t of this.game.particles.texts){let v=this.texts.get(t);if(!v){v=this.makeTextSprite(t.text,t.color,t.critical);this.group.add(v);this.texts.set(t,v);}const progress=1-t.life/t.max;toScene(t.x,t.y,.72+progress*.36,this._tempPoint);v.position.copy(this._tempPoint);v.quaternion.copy(this.camera.quaternion);v.material.opacity=Math.max(0,t.life/t.max);}}
  makeTextSprite(text,color,critical){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=96;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,256,96);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`800 ${critical?36:30}px ui-monospace, monospace`;ctx.lineWidth=7;ctx.strokeStyle='rgba(8,18,14,.72)';ctx.strokeText(text,128,46);ctx.fillStyle=color;ctx.fillText(text,128,46);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const mat=new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false});const sprite=new THREE.Sprite(mat);sprite.scale.set(critical?1.25:1,.42,1);return sprite;}
}
