import { ELEMENTS } from '../config/elements.js';
import { ellipse,polygon,glow,noGlow,colorWithAlpha } from './drawing.js';

export class VfxRenderer{
 constructor(game){this.game=game;}
 projectiles(c,time){for(const p of this.game.projectiles){const el=ELEMENTS[p.element];c.save();c.translate(p.x,p.y);const dx=p.x-p.prevX,dy=p.y-p.prevY,angle=Math.atan2(dy,dx);c.rotate(angle);const trail=c.createLinearGradient(-24,0,8,0);trail.addColorStop(0,'#0000');trail.addColorStop(1,colorWithAlpha(el.color,.55));c.strokeStyle=trail;c.lineWidth=p.kind==='meteor'?7:p.kind==='rock'?4:3;c.beginPath();c.moveTo(-28,0);c.lineTo(0,0);c.stroke();glow(c,el.color,p.kind==='meteor'?20:11);if(p.kind==='shard'||p.kind==='prism'){c.rotate(p.spin);polygon(c,[[0,-9],[4,0],[0,9],[-4,0]],el.light,'#fff',1);}else if(p.kind==='rock'){polygon(c,[[-7,-5],[2,-8],[8,-1],[4,7],[-5,6]],'#8a7258','#342d27',1.5);c.strokeStyle=el.color;c.lineWidth=1;c.beginPath();c.moveTo(-4,-1);c.lineTo(4,2);c.stroke();}else if(p.kind==='meteor'){ellipse(c,0,0,9,8,'#3b2018');ellipse(c,1,-1,6,5,'#ff6b2f');ellipse(c,2,-2,2.5,2.5,'#ffd279');}else if(p.kind==='thorn'||p.kind==='seed'){polygon(c,[[-7,0],[3,-4],[9,0],[3,4]],p.kind==='seed'?'#b3e681':'#79b653');}else if(p.kind==='arc'){ellipse(c,0,0,6,6,el.light);c.strokeStyle=el.color;c.beginPath();c.arc(0,0,10,-1,1);c.stroke();}else ellipse(c,0,0,5,5,el.light);noGlow(c);c.restore();}}
 particles(c){for(const p of this.game.particles.items){const life=Math.max(0,p.life/p.max);c.save();c.globalAlpha=life;c.translate(p.x,p.y);c.rotate(p.rot||0);if(p.glow){glow(c,p.color,p.glow);}if(p.type==='smoke'){ellipse(c,0,0,p.r*1.4,p.r,p.color);}else if(p.type==='shard'){polygon(c,[[0,-p.r*1.7],[p.r*.65,p.r],[0,p.r*.55],[-p.r*.65,p.r]],p.color);}else if(p.type==='leaf'){ellipse(c,0,0,p.r*1.5,p.r*.55,p.color);}else if(p.type==='spark'){c.strokeStyle=p.color;c.lineWidth=Math.max(1,p.r*.6);c.beginPath();c.moveTo(-p.r,0);c.lineTo(p.r,0);c.stroke();}else if(p.type==='dust'){ellipse(c,0,0,p.r*1.2,p.r*.7,p.color);}else ellipse(c,0,0,p.r,p.r,p.color);noGlow(c);c.restore();}
  for(const r of this.game.particles.rings){const life=Math.max(0,r.life/r.max),radius=r.from+(r.to-r.from)*(1-life);c.save();c.globalAlpha=life*.8;c.strokeStyle=r.color;c.lineWidth=r.width*life+1;c.beginPath();c.ellipse(r.x,r.y,radius,radius*(r.aspect||1),0,0,Math.PI*2);c.stroke();c.restore();}
  for(const b of this.game.particles.beams){c.save();c.globalAlpha=Math.max(0,b.life/b.max);glow(c,b.color,12);c.strokeStyle=b.color;c.lineWidth=b.width||2.5;c.lineJoin='round';c.beginPath();b.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();c.globalAlpha*=.5;c.strokeStyle='#ffffff';c.lineWidth=.8;c.stroke();noGlow(c);c.restore();}
  c.textAlign='center';c.textBaseline='middle';for(const t of this.game.particles.texts){const life=Math.max(0,t.life/t.max),ease=1-life;c.save();c.globalAlpha=Math.min(1,life*2);c.translate(t.x,t.y-ease*24);c.font=`${t.critical?'800':'700'} ${t.size||12}px ui-sans-serif,system-ui`;c.lineWidth=3;c.strokeStyle='#07100dcc';c.strokeText(t.text,0,0);c.fillStyle=t.color;c.fillText(t.text,0,0);c.restore();}}
 }
