import * as THREE from 'three';
import { BUILD_PADS, PATH } from '../config/map.js';
import { SURFACE_TYPES, SHRINES, TOWER_TRAITS, VETERANCY_RANKS } from '../config/worldStrategy.js';
import { SCENE_SCALE, toScene } from './drawing.js';

export class WorldStrategyRenderer{
 constructor(game,scene){this.game=game;this.scene=scene;this.root=new THREE.Group();this.root.name='world-strategy-layer';this.scene.add(this.root);this.matrix=new THREE.Matrix4();this.quat=new THREE.Quaternion().setFromEuler(new THREE.Euler(-Math.PI/2,0,0));this.scale=new THREE.Vector3();this.pos=new THREE.Vector3();this.color=new THREE.Color();this.maxSurface=48;this.maxScar=52;this.maxRoles=18;this.maxProjectiles=16;this.maxPads=18;this.maxHeat=180;this.routeId=null;this.buildInstances();this.buildShrines();this.buildEvolution();this.routeOverlay=new THREE.Group();this.routeOverlay.name='dynamic-route-overlay';this.root.add(this.routeOverlay);}
 buildInstances(){
   const circle=new THREE.CircleGeometry(1,32),ring=new THREE.RingGeometry(.76,1,28),small=new THREE.IcosahedronGeometry(.08,1);
   this.surfaceMesh=new THREE.InstancedMesh(circle,new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.18,depthWrite:false,vertexColors:true,side:THREE.DoubleSide}),this.maxSurface);
   this.scarMesh=new THREE.InstancedMesh(ring,new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.15,depthWrite:false,vertexColors:true,side:THREE.DoubleSide}),this.maxScar);
   this.roleMesh=new THREE.InstancedMesh(ring,new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.68,depthWrite:false,vertexColors:true,side:THREE.DoubleSide}),this.maxRoles);
   this.projectileMesh=new THREE.InstancedMesh(small,new THREE.MeshBasicMaterial({color:'#ffffff',vertexColors:true}),this.maxProjectiles);
   this.padMesh=new THREE.InstancedMesh(ring,new THREE.MeshBasicMaterial({color:'#ff9a74',transparent:true,opacity:.7,depthWrite:false,vertexColors:true,side:THREE.DoubleSide}),this.maxPads);
   this.heatMesh=new THREE.InstancedMesh(circle,new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.13,depthWrite:false,vertexColors:true,side:THREE.DoubleSide}),this.maxHeat);
   for(const m of[this.surfaceMesh,this.scarMesh,this.roleMesh,this.projectileMesh,this.padMesh,this.heatMesh]){m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);m.frustumCulled=false;this.root.add(m);}
 }
 buildShrines(){this.shrineRoots=new Map();for(const shrine of SHRINES){const root=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(.28,.34,.12,12),new THREE.MeshStandardMaterial({color:'#526b5c',roughness:.75}));const core=new THREE.Mesh(new THREE.OctahedronGeometry(.14,0),new THREE.MeshStandardMaterial({color:'#d8f2df',emissive:'#9ad2b0',emissiveIntensity:.42,roughness:.32}));core.position.y=.23;const radius=Math.max(.35,shrine.radius*SCENE_SCALE);const area=new THREE.Mesh(new THREE.RingGeometry(radius-.018,radius+.018,48),new THREE.MeshBasicMaterial({color:'#9ccfb2',transparent:true,opacity:.12,depthWrite:false,side:THREE.DoubleSide}));area.rotation.x=-Math.PI/2;area.position.y=.015;root.add(base,core,area);toScene(shrine.x,shrine.y,.1,root.position);this.root.add(root);this.shrineRoots.set(shrine.id,{root,core,area});}}
 buildEvolution(){this.evolution=[];const specs=[{state:1,x:1190,y:650,color:'#d2b879',kind:'wall'},{state:1,x:1160,y:620,color:'#d2b879',kind:'wall'},{state:2,x:1030,y:545,color:'#ff8b55',kind:'crystal'},{state:2,x:820,y:540,color:'#d49362',kind:'crystal'},{state:3,x:1260,y:360,color:'#bf7dff',kind:'crystal'},{state:3,x:1320,y:420,color:'#ca8cff',kind:'crystal'}];for(const spec of specs){const geo=spec.kind==='wall'?new THREE.BoxGeometry(.42,.22,.14):new THREE.ConeGeometry(.13,.46,5),mat=new THREE.MeshStandardMaterial({color:spec.color,emissive:spec.kind==='crystal'?spec.color:'#000000',emissiveIntensity:spec.kind==='crystal'?.38:0,roughness:.65});const mesh=new THREE.Mesh(geo,mat);toScene(spec.x,spec.y,spec.kind==='wall'?.18:.3,mesh.position);mesh.visible=false;this.root.add(mesh);this.evolution.push({mesh,state:spec.state});}}
 syncEvolution(){const state=this.game.world?.map?.mapState||0;for(const item of this.evolution)item.mesh.visible=state>=item.state;}
 syncRoute(){const id=this.game.world?.map?.activeRoute||'standard';if(id===this.routeId)return;this.routeId=id;for(const child of [...this.routeOverlay.children]){child.geometry?.dispose?.();child.material?.dispose?.();this.routeOverlay.remove(child);}for(let i=1;i<PATH.length;i++){const a=PATH[i-1],b=PATH[i],dx=(b.x-a.x)*SCENE_SCALE,dz=(b.y-a.y)*SCENE_SCALE,len=Math.hypot(dx,dz),mesh=new THREE.Mesh(new THREE.PlaneGeometry(len,.34),new THREE.MeshBasicMaterial({color:id==='standard'?'#d8c59c':'#e0b77f',transparent:true,opacity:id==='standard'?.035:.16,depthWrite:false,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.rotation.z=-Math.atan2(dz,dx);toScene((a.x+b.x)/2,(a.y+b.y)/2,.092,mesh.position);this.routeOverlay.add(mesh);}}
 setInstance(mesh,index,x,y,height,radius,color,rotation=this.quat){toScene(x,y,height,this.pos);this.scale.set(radius*SCENE_SCALE,radius*SCENE_SCALE,1);this.matrix.compose(this.pos,rotation,this.scale);mesh.setMatrixAt(index,this.matrix);this.color.set(color);mesh.setColorAt(index,this.color);}
 hideRest(mesh,start){mesh.count=start;mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}
 sync(time){const world=this.game.world;if(!world)return;const budget=world.performance;const surfaceLimit=Math.min(this.maxSurface,budget?.surfaceLimit||32),scarLimit=Math.min(this.maxScar,budget?.scarLimit||40);let i=0;for(const s of world.surfaces.surfaces.slice(-surfaceLimit)){this.setInstance(this.surfaceMesh,i++,s.x,s.y,.105,s.radius*(.92+.05*Math.sin(time*2+s.id)),SURFACE_TYPES[s.type]?.color||'#ffffff');}this.hideRest(this.surfaceMesh,i);i=0;for(const s of world.surfaces.scars.slice(-scarLimit)){this.setInstance(this.scarMesh,i++,s.x,s.y,.098,s.radius,SURFACE_TYPES[s.type]?.color||'#8c8c8c');}this.hideRest(this.scarMesh,i);i=0;for(const enemy of this.game.enemies){if(i>=this.maxRoles)break;let color=null,radius=enemy.def.size*1.55;if(enemy.modifiers?.has('commander'))color='#ffba78';else if(enemy.modifiers?.has('saboteur'))color='#ff7b8b';else if(enemy.weakPointOpen&&(enemy.def.boss||enemy.def.id==='tank'||enemy.def.id==='elite')){color='#fff0a8';radius*=.72;}if(!color)continue;this.setInstance(this.roleMesh,i++,enemy.x,enemy.y,.12,radius,color);}this.hideRest(this.roleMesh,i);i=0;for(const p of world.enemies.enemyProjectiles){if(i>=this.maxProjectiles)break;this.setInstance(this.projectileMesh,i++,p.x,p.y,.45+Math.sin(time*8+p.id)*.06,100,p.color||'#e8b8ff',new THREE.Quaternion());}this.hideRest(this.projectileMesh,i);i=0;for(const pad of BUILD_PADS){const locked=world.map.lockedPads.has(pad.id),disabled=world.map.disabledPads.has(pad.id);if(!locked&&!disabled)continue;this.setInstance(this.padMesh,i++,pad.x,pad.y,.13,pad.r*1.22,disabled?'#ff6c53':'#a48b7c');}this.hideRest(this.padMesh,i);for(const[id,view]of this.shrineRoots){const state=world.map.shrines.get(id);view.core.material.emissiveIntensity=state?.active?.95:.28;view.area.material.opacity=state?.active?.32:.09;view.root.rotation.y+=.002;}this.syncRoute();this.syncEvolution();this.syncHeatmap();this.syncTowerIdentity(time);this.syncPresentation();}
 syncTowerIdentity(time){for(const tower of this.game.towers){const art=this.game.renderer?.towerArt?.models?.get?.(tower);if(!art)continue;const rank=VETERANCY_RANKS.find(r=>r.id===tower.veterancy),trait=TOWER_TRAITS.find(t=>t.id===tower.trait);art.scale.y=1+(tower.legendary?.08:rank?.id==='master'?.04:rank?.id==='elite'?.025:0);if(trait&&art.userData?.worldTrait!==trait.id){art.userData.worldTrait=trait.id;const rune=new THREE.Mesh(new THREE.TorusGeometry(.21,.018,6,20),new THREE.MeshBasicMaterial({color:trait.color,transparent:true,opacity:.55,depthWrite:false}));rune.rotation.x=Math.PI/2;rune.position.y=.82;art.add(rune);}if(tower.legendary)art.rotation.y+=Math.sin(time*1.4+tower.phase)*.0008;}}
 syncPresentation(){const state=this.game.world?.map?.mapState||0,renderer=this.game.renderer;if(!renderer?.webgl)return;const intensity=this.game.world?.battleIntensity||0;renderer.webgl.toneMappingExposure+=(state>=3?-.035:state>=2?-.015:0)+intensity*.018;}
 syncHeatmap(){const world=this.game.world,mode=world?.heatmapMode;let points=[];if(mode==='deaths')points=world.analytics.deaths.slice(-this.maxHeat).map(p=>({...p,radius:p.boss?48:20,color:p.boss?'#ff8a63':'#ffca7d'}));else if(mode==='damage')points=world.analytics.damageHeat.slice(-this.maxHeat).map(p=>({...p,radius:Math.min(48,12+Math.log2(1+p.value)*3.2),color:'#ff9c63'}));else if(mode==='coverage')points=(this.game.towers||[]).slice(0,this.maxHeat).map(t=>({x:t.x,y:t.y,radius:t.stats.range,color:t.def.element==='fire'?'#ff7040':t.def.element==='ice'?'#79eaff':t.def.element==='lightning'?'#9fcfff':t.def.element==='nature'?'#7fdf75':t.def.element==='earth'?'#d9a467':'#c08aff'}));let i=0;for(const p of points){this.setInstance(this.heatMesh,i++,p.x,p.y,.087,p.radius,p.color);}this.hideRest(this.heatMesh,i);this.heatMesh.visible=Boolean(mode);}
 setHeatmapVisible(value){this.game.world.heatmapMode=value?'deaths':null;this.game.world.showHeatmap=Boolean(value);}
 dispose(){for(const child of [...this.root.children]){child.geometry?.dispose?.();if(Array.isArray(child.material))child.material.forEach(m=>m.dispose?.());else child.material?.dispose?.();}this.scene.remove(this.root);}
}
