const clamp01=v=>Math.max(0,Math.min(1,Number(v)||0));const midi=n=>440*2**((n-69)/12);
export class AudioManager{
  constructor(game){this.game=game;const saved=JSON.parse(localStorage.getItem('towerdefnapst.settings')||'{}');this.music=saved.music??.42;this.sfx=saved.sfx??.7;this.muted=saved.muted??false;this.ctx=null;this.musicGain=null;this.sfxGain=null;this.ambienceGain=null;this.musicState='calm';this.pendingMusicState='calm';this.scheduler=null;this.nextStepTime=0;this.step=0;this.bar=0;this.bpm=116;this.noiseBuffer=null;this.pluckCache=new Map();this.lastSfx=new Map();}
  ensure(){if(!this.ctx)this.setupContext();if(this.ctx.state==='suspended')this.ctx.resume();if(!this.scheduler)this.startScore();}
  setupContext(){this.ctx=new(window.AudioContext||window.webkitAudioContext)();const master=this.ctx.createDynamicsCompressor();master.threshold.value=-8;master.knee.value=10;master.ratio.value=4;master.attack.value=.004;master.release.value=.16;master.connect(this.ctx.destination);this.musicGain=this.ctx.createGain();this.sfxGain=this.ctx.createGain();this.ambienceGain=this.ctx.createGain();this.musicGain.gain.value=this.muted?0:this.music*.5;this.sfxGain.gain.value=this.muted?0:this.sfx*.72;this.ambienceGain.gain.value=this.muted?0:this.music*.08;this.musicGain.connect(master);this.sfxGain.connect(master);this.ambienceGain.connect(master);this.noiseBuffer=this.makeNoiseBuffer(2);this.startAmbience();}
  makeNoiseBuffer(seconds){const length=Math.floor(this.ctx.sampleRate*seconds),buffer=this.ctx.createBuffer(1,length,this.ctx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<length;i++){const white=Math.random()*2-1;last=last*.72+white*.28;data[i]=last;}return buffer;}
  startAmbience(){const source=this.ctx.createBufferSource();source.buffer=this.noiseBuffer;source.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=460;filter.Q.value=.35;source.connect(filter).connect(this.ambienceGain);source.start();this.ambienceSource=source;}
  startScore(){this.nextStepTime=this.ctx.currentTime+.08;this.scheduler=window.setInterval(()=>this.scheduleAhead(),80);this.scheduleAhead();}
  scheduleAhead(){if(!this.ctx||this.ctx.state!=='running')return;const horizon=this.ctx.currentTime+.32;while(this.nextStepTime<horizon){if(this.step===0)this.musicState=this.pendingMusicState;this.scheduleStep(this.step,this.nextStepTime);const target=this.musicState==='boss'?128:this.musicState==='wave'?122:114;this.bpm+=(target-this.bpm)*.22;this.nextStepTime+=(60/this.bpm)/4;this.step=(this.step+1)%16;if(this.step===0)this.bar++;}}
  scheduleStep(step,time){const state=this.musicState;if(state==='defeat'){if(step===0)this.pluck(midi(38),time,.9,.045,.25,this.musicGain);return;}if(state==='victory'){const motif=[62,65,69,74];if(step%4===0)this.pluck(midi(motif[(step/4)%4]),time,.65,.05,.62,this.musicGain);if(step===0||step===8)this.horn(midi(step===0?50:55),time,.5,.045);return;}const progression=[50,46,48,45],root=progression[this.bar%4],chord=[root,root+3,root+7,root+12],boss=state==='boss',wave=state==='wave'||boss;if(step===0||step===8||(wave&&(step===6||step===14))||(boss&&(step===3||step===11)))this.kick(time,boss?.105:wave?.09:.065);if(step===4||step===12)this.snare(time,boss?.075:wave?.062:.045);if((wave&&step%2===0)||(!wave&&[2,6,10,14].includes(step)))this.hat(time,wave?.022:.014,step%4===2);if(boss&&(step===7||step===15))this.tom(time,step===15?104:128,.05);if(step%(wave?2:4)===0){const note=chord[(step/(wave?2:4)+this.bar)%chord.length];this.pluck(midi(note+12),time,.46,wave?.03:.025,.78,this.musicGain);if(wave&&step%4===0)this.pluck(midi(note+19),time+.018,.35,.014,.85,this.musicGain);}if(step%4===0){const bass=step===12?root+7:root;this.pluck(midi(bass-12),time,.62,wave?.045:.032,.28,this.musicGain);}if(wave&&step===0&&this.bar%2===0)this.horn(midi(root),time,.42,boss?.04:.026);if(boss&&step===8)this.horn(midi(root+7),time,.36,.034);}
  makePluckBuffer(freq,duration=.75,brightness=.65){const key=`${Math.round(freq)}-${Math.round(duration*10)}-${Math.round(brightness*10)}`;if(this.pluckCache.has(key))return this.pluckCache.get(key);const length=Math.floor(this.ctx.sampleRate*duration),delay=Math.max(2,Math.floor(this.ctx.sampleRate/freq)),buffer=this.ctx.createBuffer(1,length,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<Math.min(delay,length);i++)data[i]=(Math.random()*2-1)*(.7+brightness*.3);const damping=.988-brightness*.006;for(let i=delay;i<length;i++){const prev=data[i-delay],neighbor=data[i-delay+1]||prev;data[i]=(prev*.55+neighbor*.45)*damping;}this.pluckCache.set(key,buffer);if(this.pluckCache.size>70)this.pluckCache.delete(this.pluckCache.keys().next().value);return buffer;}
  pluck(freq,time,duration,gain,brightness,output){const source=this.ctx.createBufferSource();source.buffer=this.makePluckBuffer(freq,Math.max(.45,duration),brightness);source.playbackRate.value=.985+Math.random()*.03;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1100+brightness*3800;filter.Q.value=.35;const env=this.ctx.createGain();env.gain.setValueAtTime(.0001,time);env.gain.exponentialRampToValueAtTime(gain,time+.008);env.gain.exponentialRampToValueAtTime(.0001,time+duration);source.connect(filter).connect(env).connect(output);source.start(time);source.stop(time+duration+.04);}
  noiseTap(time,duration,gain,frequency,type,output,q=.5){const source=this.ctx.createBufferSource();source.buffer=this.noiseBuffer;const filter=this.ctx.createBiquadFilter();filter.type=type;filter.frequency.value=frequency;filter.Q.value=q;const env=this.ctx.createGain();env.gain.setValueAtTime(Math.max(.0001,gain),time);env.gain.exponentialRampToValueAtTime(.0001,time+duration);source.connect(filter).connect(env).connect(output);source.start(time,Math.random()*.8);source.stop(time+duration+.02);}
  kick(time,gain){const o=this.ctx.createOscillator(),e=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(138,time);o.frequency.exponentialRampToValueAtTime(52,time+.095);e.gain.setValueAtTime(gain,time);e.gain.exponentialRampToValueAtTime(.0001,time+.17);o.connect(e).connect(this.musicGain);o.start(time);o.stop(time+.18);this.noiseTap(time,.025,gain*.22,1800,'highpass',this.musicGain);}
  snare(time,gain){this.noiseTap(time,.16,gain,1450,'bandpass',this.musicGain,.8);const o=this.ctx.createOscillator(),e=this.ctx.createGain();o.type='triangle';o.frequency.value=185;e.gain.setValueAtTime(gain*.28,time);e.gain.exponentialRampToValueAtTime(.0001,time+.09);o.connect(e).connect(this.musicGain);o.start(time);o.stop(time+.1);}
  hat(time,gain,open=false){this.noiseTap(time,open?.11:.045,gain,6100,'highpass',this.musicGain,.25);}
  tom(time,freq,gain){const o=this.ctx.createOscillator(),e=this.ctx.createGain();o.type='triangle';o.frequency.setValueAtTime(freq*1.35,time);o.frequency.exponentialRampToValueAtTime(freq,time+.12);e.gain.setValueAtTime(gain,time);e.gain.exponentialRampToValueAtTime(.0001,time+.24);o.connect(e).connect(this.musicGain);o.start(time);o.stop(time+.25);}
  horn(freq,time,duration,gain){const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1900;filter.Q.value=.6;const env=this.ctx.createGain();env.gain.setValueAtTime(.0001,time);env.gain.linearRampToValueAtTime(gain,time+.035);env.gain.exponentialRampToValueAtTime(.0001,time+duration);filter.connect(env).connect(this.musicGain);[1,2,3].forEach((h,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=freq*h;g.gain.value=[1,.32,.13][i];o.connect(g).connect(filter);o.start(time);o.stop(time+duration+.02);});}
  setMusicState(state){this.pendingMusicState=state;if(!this.ctx)return;if(state==='boss')this.playUi('boss');if(state==='victory')this.playUi('victory');}
  canPlay(key,gap){if(this.muted||this.sfx<=0)return false;this.ensure();const now=this.ctx.currentTime;if(now-(this.lastSfx.get(key)??-999)<gap)return false;this.lastSfx.set(key,now);return true;}
  sfxOsc(freq,duration,type,gain,drop=.72,when=0){const time=this.ctx.currentTime+when,o=this.ctx.createOscillator(),e=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);o.frequency.exponentialRampToValueAtTime(Math.max(45,freq*drop),time+duration);e.gain.setValueAtTime(gain,time);e.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(e).connect(this.sfxGain);o.start(time);o.stop(time+duration+.02);}
  playShot(tower){const def=tower.def,j=.94+Math.random()*.12;if(!this.canPlay(`shot-${def.id}`,def.rate>1.8?.045:.025))return;if(def.projectile==='meteor'){this.sfxOsc(92*j,.18,'triangle',.16,.45);this.noiseTap(this.ctx.currentTime,.12,.085,700,'lowpass',this.sfxGain,.8);}else if(def.projectile==='rock'){this.sfxOsc(128*j,.12,'triangle',.12,.55);this.noiseTap(this.ctx.currentTime,.075,.055,1100,'bandpass',this.sfxGain,.9);}else if(def.projectile==='arc'){this.noiseTap(this.ctx.currentTime,.035,.065,5200,'highpass',this.sfxGain,.4);this.sfxOsc(680*j,.055,'sine',.055,.42);}else if(def.projectile==='bolt'){this.noiseTap(this.ctx.currentTime,.045,.05,3400,'bandpass',this.sfxGain,2.2);this.sfxOsc(920*j,.04,'triangle',.035,.3);}else if(def.element==='ice'){this.pluck(980*j,this.ctx.currentTime,.16,.055,.95,this.sfxGain);this.sfxOsc(1500*j,.045,'sine',.025,.72);}else if(def.element==='nature')this.pluck(320*j,this.ctx.currentTime,.12,.07,.5,this.sfxGain);else{this.noiseTap(this.ctx.currentTime,.045,.048,2400,'bandpass',this.sfxGain,.7);this.sfxOsc(330*j,.07,'triangle',.055,.62);}}
  playImpact(projectile,enemy){const heavy=projectile.splash>45||projectile.kind==='meteor',key=heavy?'impact-heavy':`impact-${projectile.element}`;if(!this.canPlay(key,heavy?.07:.035))return;const armor=(enemy?.armor||enemy?.def?.armor||0)>.07;if(heavy){this.sfxOsc(72,.24,'sine',.17,.45);this.noiseTap(this.ctx.currentTime,.24,.12,620,'lowpass',this.sfxGain,.55);}else if(projectile.element==='ice'){this.pluck(1320,this.ctx.currentTime,.16,.05,.96,this.sfxGain);this.noiseTap(this.ctx.currentTime,.06,.035,5200,'highpass',this.sfxGain);}else if(projectile.element==='fire')this.noiseTap(this.ctx.currentTime,.095,.065,1100,'bandpass',this.sfxGain,.5);else if(armor){this.sfxOsc(245,.055,'square',.035,.8);this.noiseTap(this.ctx.currentTime,.055,.04,3200,'bandpass',this.sfxGain,2.5);}else this.noiseTap(this.ctx.currentTime,.055,.04,1900,'bandpass',this.sfxGain,.8);}
  playBuild(){if(!this.canPlay('build',.08))return;this.pluck(midi(60),this.ctx.currentTime,.24,.075,.7,this.sfxGain);this.pluck(midi(67),this.ctx.currentTime+.055,.28,.055,.75,this.sfxGain);}
  playUpgrade(){if(!this.canPlay('upgrade',.12))return;[62,67,74].forEach((n,i)=>this.pluck(midi(n),this.ctx.currentTime+i*.055,.3,.055,.82,this.sfxGain));}
  playSpawn(){if(!this.canPlay('spawn',.11))return;this.noiseTap(this.ctx.currentTime,.18,.035,850,'lowpass',this.sfxGain,.7);}
  playWaveComplete(){if(!this.canPlay('wave-complete',.4))return;[62,65,69].forEach((n,i)=>this.pluck(midi(n),this.ctx.currentTime+i*.075,.4,.052,.75,this.sfxGain));}
  playUi(name){if(!this.canPlay(`ui-${name}`,name==='boss'?.22:.08))return;const presets={sell:[310,.1,'triangle',.055,.72],leak:[105,.18,'triangle',.095,.52],boss:[78,.38,'triangle',.12,.4],victory:[520,.24,'sine',.075,1.35],click:[440,.045,'sine',.03,.82]};this.sfxOsc(...(presets[name]??presets.click));}
  save(){localStorage.setItem('towerdefnapst.settings',JSON.stringify({music:this.music,sfx:this.sfx,muted:this.muted}));}
  setMusic(value){this.music=clamp01(value);if(this.musicGain)this.musicGain.gain.setTargetAtTime(this.muted?0:this.music*.5,this.ctx.currentTime,.08);if(this.ambienceGain)this.ambienceGain.gain.setTargetAtTime(this.muted?0:this.music*.08,this.ctx.currentTime,.12);this.save();}
  setSfx(value){this.sfx=clamp01(value);if(this.sfxGain)this.sfxGain.gain.setTargetAtTime(this.muted?0:this.sfx*.72,this.ctx.currentTime,.05);this.save();}
  toggleMute(){this.muted=!this.muted;if(this.musicGain)this.musicGain.gain.setTargetAtTime(this.muted?0:this.music*.5,this.ctx.currentTime,.05);if(this.sfxGain)this.sfxGain.gain.setTargetAtTime(this.muted?0:this.sfx*.72,this.ctx.currentTime,.05);if(this.ambienceGain)this.ambienceGain.gain.setTargetAtTime(this.muted?0:this.music*.08,this.ctx.currentTime,.05);this.save();return this.muted;}
}
