import { Projectile } from '../entities/Projectile.js';
import { elementalMultiplier,ELEMENTS } from '../config/elements.js';
export class CombatSystem{
 constructor(game){this.game=game;}
 update(dt){for(const t of this.game.towers){t.update(dt);if(t.cooldown>0)continue;const target=this.pickTarget(t);if(!target)continue;this.fire(t,target);}}
 pickTarget(tower){const r2=tower.stats.range**2;let list=this.game.enemies.filter(e=>!e.dead&&(e.x-tower.x)**2+(e.y-tower.y)**2<=r2);if(!list.length)return null;switch(tower.targetMode){case'last':list.sort((a,b)=>a.distance-b.distance);break;case'strong':list.sort((a,b)=>b.hp-a.hp);break;case'weak':list.sort((a,b)=>a.hp-b.hp);break;case'closest':list.sort((a,b)=>((a.x-tower.x)**2+(a.y-tower.y)**2)-((b.x-tower.x)**2+(b.y-tower.y)**2));break;default:list.sort((a,b)=>b.distance-a.distance);}return list[0];}
 fire(t,target){const s=t.stats,def=t.def;let rate=s.rate;for(const ally of this.game.towers){if(ally===t||!ally.def.auraRate)continue;if((ally.x-t.x)**2+(ally.y-t.y)**2<=(ally.def.auraRadius||0)**2)rate*=1+ally.def.auraRate;}t.cooldown=1/rate;t.flash=1;t.angle=Math.atan2(target.y-t.y,target.x-t.x);this.game.audio.play('shoot');if(def.projectile==='bolt'){this.chain(t,target,s.damage);return;}this.game.projectiles.push(new Projectile({tower:t,target,damage:s.damage,element:def.element,kind:def.projectile,splash:s.splash,meta:def,speed:def.projectile==='meteor'?330:def.projectile==='rock'?390:540}));}
 chain(t,target,damage){const hit=[];let current=target,amount=damage;const max=t.def.chain||3;for(let i=0;i<max&&current;i++){hit.push(current);this.damage(t,current,amount);const next=this.game.enemies.filter(e=>!e.dead&&!hit.includes(e)&&Math.hypot(e.x-current.x,e.y-current.y)<105).sort((a,b)=>Math.hypot(a.x-current.x,a.y-current.y)-Math.hypot(b.x-current.x,b.y-current.y))[0];amount*=t.def.chainFalloff||.72;current=next;}this.game.particles.beam([{x:t.x,y:t.y-15},...hit.map(e=>({x:e.x,y:e.y}))],ELEMENTS.lightning.color);}
 impact(p){const t=p.tower,target=p.target;if(!target||target.dead)return;this.damage(t,target,p.damage);if(p.splash>0){for(const e of this.game.enemies){if(e!==target&&!e.dead&&Math.hypot(e.x-target.x,e.y-target.y)<=p.splash)this.damage(t,e,p.damage*.55,true);}}this.game.particles.burst(target.x,target.y,ELEMENTS[p.element].color,p.splash?12:6,p.splash?90:45);this.game.audio.play('impact');}
 damage(t,e,base,isSplash=false){if(e.dead)return;const d=t.def;const mult=elementalMultiplier(d.element,e,d.penetration||0);let amount=base*mult;if(d.pureFraction){const pure=base*d.pureFraction;amount=base*(1-d.pureFraction)*mult+pure;}if(e.effects.has('mark'))amount*=e.effects.get('mark').amount||1;const before=e.hp+e.shield;const dealt=e.takeRawDamage(amount);t.damageDone+=dealt;if(d.burn&&!e.dead)e.addEffect('burn',{remaining:d.burnDuration||3,dps:d.burn*(.8+t.level*.2),source:t});if(d.poison&&!e.dead)e.addEffect('poison',{remaining:d.poisonDuration||4,dps:d.poison*(.8+t.level*.2),stacks:1,source:t});if(d.slow&&!e.dead)e.addEffect('slow',{remaining:d.slowDuration||2,amount:d.slow});if(d.freezeChance&&!e.dead&&Math.random()<d.freezeChance)e.addEffect('freeze',{remaining:.55+.12*t.level});if(d.stunChance&&!e.dead&&Math.random()<d.stunChance)e.addEffect('stun',{remaining:d.stunDuration||.5});if(d.mark&&!e.dead)e.addEffect('mark',{remaining:d.markDuration||3,amount:d.mark});if(d.conductive&&e.effects.has('slow')){e.takeRawDamage(base*.2);this.game.particles.burst(e.x,e.y,ELEMENTS.lightning.color,3,25);}if(e.dead&&before>0)this.kill(t,e);}
 kill(t,e){if(e.escaped||e._rewarded)return;e._rewarded=true;if(t)t.kills++;this.game.state.reward(e.reward);this.game.state.score+=Math.round(e.maxHp);this.game.particles.burst(e.x,e.y,e.def.color,e.def.boss?28:9,e.def.boss?150:70);}
}
