import { ELEMENTS } from '../config/elements.js';

export class ParticleSystem{
  constructor(){this.items=[];this.pool=[];this.beams=[];this.rings=[];this.texts=[];this.bursts=[];this.burstPool=[];this.decals=[];this.decalPool=[];this.maxParticles=900;this.maxBursts=48;this.maxDecals=42;}
  acquire(){return this.pool.pop()||{};}
  spawn(x,y,{color='#fff',count=1,power=50,type='orb',r=2,life=.5,gravity=0,drag=.95,glow=0,upBias=0,spread=1,height=.18}={}){const n=Math.min(48,count);for(let i=0;i<n;i++){const p=this.acquire(),angle=Math.random()*Math.PI*2,speed=power*(.28+Math.random()*.85)*spread;p.x=x;p.y=y;p.vx=Math.cos(angle)*speed;p.vy=Math.sin(angle)*speed-upBias;p.r=r*(.65+Math.random()*.8);p.life=life*(.68+Math.random()*.55);p.max=p.life;p.color=color;p.type=type;p.gravity=gravity;p.drag=drag;p.glow=glow;p.height=height;p.rot=Math.random()*Math.PI*2;p.spin=(Math.random()-.5)*6;this.items.push(p);}if(this.items.length>this.maxParticles){const excess=this.items.length-this.maxParticles;for(let i=0;i<excess;i++)this.pool.push(this.items.shift());}}
  muzzle(tower,target){const el=ELEMENTS[tower.def.element],angle=Math.atan2(target.y-tower.y,target.x-tower.x),x=tower.x+Math.cos(angle)*22,y=tower.y+Math.sin(angle)*22,projectile=tower.def.projectile,type=projectile==='meteor'||projectile==='rock'?'spark':tower.def.element==='nature'?'leaf':tower.def.element==='ice'?'shard':'spark',count=projectile==='meteor'?10:projectile==='rock'?7:tower.level+3;this.spawn(x,y,{color:el.light,count,power:projectile==='meteor'?72:42,type,r:2.3,life:.22,glow:10,upBias:3,height:.78});if(projectile==='meteor'||projectile==='rock')this.spawn(x,y,{color:'#d4c1a4',count:3,power:28,type:'smoke',r:5,life:.45,drag:.97,upBias:12,height:.72});}
  impact(element,x,y,kind='orb',heavy=false){const el=ELEMENTS[element];if(element==='fire'){this.spawn(x,y,{color:'#ffb04a',count:heavy?22:10,power:heavy?125:72,type:'spark',r:2.5,life:.42,glow:10});this.spawn(x,y,{color:'#6d5b52',count:heavy?11:4,power:heavy?48:30,type:'smoke',r:heavy?7:5,life:heavy?1.05:.7,gravity:-10,drag:.975,upBias:18});if(heavy||kind==='meteor')this.explosion(x,y,'#ff7a35',heavy?1.15:.8);this.decal('scorch',x,y,'#39271f',heavy?.78:.46,heavy?5.6:3.8);}else if(element==='ice'){this.spawn(x,y,{color:el.light,count:heavy?20:10,power:heavy?108:64,type:'shard',r:3,life:.56,gravity:18,glow:7});this.burstEvent('ice',x,y,el.light,heavy?.8:.52,.42);this.decal('frost',x,y,'#bdefff',heavy?.72:.42,3.4);}else if(element==='lightning'){this.spawn(x,y,{color:el.light,count:heavy?18:8,power:110,type:'spark',r:2.2,life:.2,glow:14});this.burstEvent('flash',x,y,el.light,.55,.15);}else if(element==='nature'){this.spawn(x,y,{color:el.color,count:heavy?16:9,power:68,type:'leaf',r:3.2,life:.55,gravity:9});this.spawn(x,y,{color:'#bfe39e',count:4,power:42,type:'orb',r:2.3,life:.4,glow:5});this.decal('poison',x,y,'#79d85f',.38,3.2);}else if(element==='earth'){this.spawn(x,y,{color:'#c7a478',count:heavy?22:11,power:heavy?105:82,type:'debris',r:3.5,life:.58,gravity:28});this.spawn(x,y,{color:'#91816d',count:heavy?10:4,power:44,type:'dust',r:5.5,life:.72,drag:.97,upBias:16});if(heavy)this.burstEvent('shock',x,y,'#d9bd91',.95,.38);this.decal('crack',x,y,'#665541',heavy?.72:.42,4);}else{this.spawn(x,y,{color:el.light,count:heavy?18:9,power:82,type:'orb',r:2.7,life:.46,glow:12});this.burstEvent('flash',x,y,el.light,heavy?.78:.5,.18);this.decal('rune',x,y,el.color,.35,2.8);}this.ring(x,y,el.color,4,heavy?64:34,heavy?3.2:1.8,.3,element==='earth'?.48:1);}
  explosion(x,y,color='#ff7a35',power=1){this.burstEvent('explosion',x,y,color,power,.58);this.ring(x,y,'#ffd18a',7,88*power,4.5,.34,.55);this.ring(x,y,color,3,55*power,2.4,.24,.7);this.spawn(x,y,{color:'#ffcb79',count:Math.round(9*power),power:105*power,type:'spark',r:2.2,life:.34,glow:12});this.spawn(x,y,{color:'#6e625b',count:Math.round(6*power),power:38*power,type:'smoke',r:7,life:.9,drag:.98,upBias:20});}
  burstEvent(kind,x,y,color,power=1,life=.4){const b=this.burstPool.pop()||{};Object.assign(b,{kind,x,y,color,power,life,max:life,seed:Math.random()*1000});this.bursts.push(b);if(this.bursts.length>this.maxBursts)this.burstPool.push(this.bursts.shift());}
  decal(kind,x,y,color='#fff',opacity=.4,life=3){const d=this.decalPool.pop()||{};Object.assign(d,{kind,x,y,color,opacity,life,max:life,rot:Math.random()*Math.PI*2,scale:.7+Math.random()*.45});this.decals.push(d);if(this.decals.length>this.maxDecals)this.decalPool.push(this.decals.shift());}
  build(x,y,element){const el=ELEMENTS[element];this.ring(x,y,el.color,8,48,2.5,.5,.5);this.spawn(x,y,{color:el.light,count:16,power:62,type:'spark',r:2.4,life:.6,glow:8,upBias:32});this.burstEvent('build',x,y,el.light,.75,.5);}
  upgrade(x,y,element){const el=ELEMENTS[element];this.ring(x,y,el.light,10,72,4,.7,.5);this.spawn(x,y,{color:el.light,count:28,power:82,type:'spark',r:2.8,life:.72,glow:10,upBias:45});this.burstEvent('build',x,y,el.light,1.05,.65);this.decal('rune',x,y,el.color,.48,1.8);}
  sell(x,y){this.spawn(x,y,{color:'#d6c49b',count:20,power:75,type:'dust',r:2.7,life:.55,gravity:-3,upBias:18});this.ring(x,y,'#d6c49b',10,42,2,.36,.5);}
  spawnEnemy(x,y,color,boss=false){this.spawn(x,y,{color,count:boss?22:8,power:boss?78:42,type:'smoke',r:boss?6:4,life:.72,drag:.97,upBias:18});this.spawn(x,y,{color:'#b7ffd9',count:boss?18:7,power:54,type:'spark',r:2.1,life:.36,glow:9});this.ring(x,y,'#7cf2b8',8,boss?72:42,boss?4:2.4,.42,.62);this.burstEvent('spawn',x,y,color,boss?1.25:.68,boss?.72:.42);}
  death(enemy){const element=enemy.lastDamageElement;const palette={fire:'#ff8b42',ice:'#bcefff',lightning:'#dcf7ff',nature:'#8edb78',earth:'#c7a478',arcane:'#d8adff'};const color=palette[element]||enemy.def.color;const type=element==='ice'?'shard':element==='fire'||element==='lightning'?'spark':element==='earth'||enemy.def.id==='tank'||enemy.def.boss?'debris':element==='nature'?'leaf':'dust';const power=enemy.def.boss?155:element==='earth'?92:76;this.spawn(enemy.x,enemy.y,{color,count:enemy.def.boss?38:element==='ice'?18:13,power,type,r:enemy.def.boss?4:2.8,life:enemy.def.boss?.85:.52,gravity:element==='lightning'?8:18,glow:enemy.def.boss?8:element==='fire'||element==='lightning'||element==='arcane'?6:2});if(element==='ice')this.burstEvent('ice',enemy.x,enemy.y,color,.62,.34);else if(element==='lightning')this.burstEvent('flash',enemy.x,enemy.y,color,.58,.16);else if(element==='fire')this.burstEvent('flash',enemy.x,enemy.y,color,.48,.18);this.ring(enemy.x,enemy.y,color,4,enemy.def.boss?92:38,enemy.def.boss?4:2,.45,.55);if(enemy.def.boss)this.burstEvent('explosion',enemy.x,enemy.y,color,1.45,.78);}
  waveClear(x,y){this.ring(x,y,'#9ff5c4',10,110,3.5,.75,.55);this.spawn(x,y,{color:'#d9ffe7',count:22,power:88,type:'spark',r:2.5,life:.65,glow:8,upBias:35});this.burstEvent('wave-clear',x,y,'#b6ffd0',1,.72);}
  nexus(x,y){this.ring(x,y,'#d08cff',12,92,5,.65,.65);this.spawn(x,y,{color:'#e7c4ff',count:24,power:110,type:'spark',r:3,life:.6,glow:10});this.burstEvent('flash',x,y,'#e7c4ff',1.05,.28);}
  combo(id,x,y,color){this.burstEvent('combo',x,y,color,.72,.26);this.ring(x,y,color,3,46,2.3,.3,.7);this.spawn(x,y,{color,count:7,power:58,type:id==='shatter'?'shard':'spark',r:2,life:.32,glow:8});}
  ring(x,y,color,from=5,to=40,width=2,life=.35,aspect=1){this.rings.push({x,y,color,from,to,width,life,max:life,aspect});if(this.rings.length>80)this.rings.shift();}
  beam(points,color){if(points.length<2)return;const zig=[points[0]];for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],parts=Math.max(2,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/34));for(let j=1;j<parts;j++){const t=j/parts,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,off=(Math.random()-.5)*9;zig.push({x:a.x+dx*t-dy/len*off,y:a.y+dy*t+dx/len*off});}zig.push(b);}this.beams.push({points:zig,life:.13,max:.13,color,width:3});if(this.beams.length>40)this.beams.shift();}
  damageText(x,y,text,color='#fff',critical=false,size=12){if(this.texts.length>44)return;this.texts.push({x,y,text:String(text),color,critical,size:critical?Math.max(15,size+3):size,life:.56,max:.56});}
  update(dt){for(let i=this.items.length-1;i>=0;i--){const p=this.items[i];p.life-=dt;if(p.life<=0){this.pool.push(p);this.items.splice(i,1);continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.gravity*dt;p.vx*=p.drag;p.vy*=p.drag;p.rot+=p.spin*dt;}for(const arr of[this.beams,this.rings,this.texts])for(let i=arr.length-1;i>=0;i--){arr[i].life-=dt;if(arr[i].life<=0)arr.splice(i,1);}for(let i=this.bursts.length-1;i>=0;i--){const b=this.bursts[i];b.life-=dt;if(b.life<=0){this.burstPool.push(b);this.bursts.splice(i,1);}}for(let i=this.decals.length-1;i>=0;i--){const d=this.decals[i];d.life-=dt;if(d.life<=0){this.decalPool.push(d);this.decals.splice(i,1);}}}
  clear(){while(this.items.length)this.pool.push(this.items.pop());while(this.bursts.length)this.burstPool.push(this.bursts.pop());while(this.decals.length)this.decalPool.push(this.decals.pop());this.beams.length=this.rings.length=this.texts.length=0;}
}
