export class RunAnalytics{
 constructor(game){this.game=game;this.reset()}
 reset(){this.damageByElement={fire:0,ice:0,lightning:0,nature:0,earth:0,arcane:0};this.killsByTower=new Map();this.comboCounts={};this.deaths=[];this.damageHeat=[];this.surfaces=0;this.reactions=0;this.perfectWaves=0;this.objectives=0;this.goldEarned=0;this.goldSpent=0;this.bossDamage=0;this.biggestHit={amount:0,element:null,x:0,y:0};this.bossPlatesBrokenThisWave=0;this.waveEliteEarlyKill=false;}
 onDamage({tower,enemy,dealt,element}){if(!dealt)return;const e=element||tower?.def?.element||'arcane';this.damageByElement[e]=(this.damageByElement[e]||0)+dealt;if(enemy?.def?.boss)this.bossDamage+=dealt;if(dealt>this.biggestHit.amount)this.biggestHit={amount:dealt,element:e,x:enemy?.x||0,y:enemy?.y||0};if(this.damageHeat.length<1000)this.damageHeat.push({x:enemy?.x||0,y:enemy?.y||0,value:dealt,element:e});}
 onKill({tower,enemy}){if(tower)this.killsByTower.set(tower,(this.killsByTower.get(tower)||0)+1);if(this.deaths.length<800)this.deaths.push({x:enemy.x,y:enemy.y,type:enemy.def.id,boss:Boolean(enemy.def.boss)});if(enemy.modifiers?.has?.('commander'))this.game.world?.director?.onCommanderKilled?.(Math.min(1,enemy.distance/10000));if((enemy.modifiers?.size||0)>0&&enemy.distance<5000)this.waveEliteEarlyKill=true;}
 onCombo(id){if(!id)return;this.comboCounts[id]=(this.comboCounts[id]||0)+1;}
 dominantElement(){return Object.entries(this.damageByElement).sort((a,b)=>b[1]-a[1])[0]?.[0]||'arcane';}
 towerMvp(){let best=null;for(const tower of this.game.towers||[])if(!best||tower.damageDone>best.damageDone)best=tower;return best;}
 mostCombo(){return Object.entries(this.comboCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';}
 report(){const mvp=this.towerMvp(),bestElement=this.dominantElement(),spent=this.game.state.goldSpent||this.goldSpent,earned=Math.max(this.goldEarned,0);return{score:this.game.state.score,wave:this.game.state.wave,time:this.game.state.elapsed,kills:this.game.state.kills,bosses:this.game.state.bossesKilled||0,combos:this.game.state.combos||0,surfaces:this.surfaces,reactions:this.reactions,bossDamage:Math.round(this.bossDamage),perfectWaves:this.perfectWaves,objectives:this.objectives,bestTower:mvp?.def?.name||'—',bestElement,mostCombo:this.mostCombo(),biggestHit:Math.round(this.biggestHit.amount),goldSpent:spent,goldEarned:earned,goldEfficiency:spent>0?Number((earned/spent).toFixed(2)):earned>0?Infinity:0,seed:this.game.world?.seed||'—'};}
}
