import { TOWERS } from '../config/towers.js';import { ELEMENTS } from '../config/elements.js';
export class UIManager{
 constructor(game){this.game=game;this.$=id=>document.getElementById(id);this.build();this.bind();}
 build(){const menu=this.$('buildMenu');menu.innerHTML='';for(const t of TOWERS){const el=ELEMENTS[t.element],b=document.createElement('button');b.className='tower-card';b.dataset.tower=t.id;b.style.setProperty('--element',el.color);b.title=`${t.name} — ${t.description}\n${t.damage} dégâts · ${t.range} portée · ${t.rate}/s`;b.innerHTML=`<span class="tower-icon">${el.glyph}</span><strong>${t.name}</strong><small>◈ ${t.cost}</small>`;menu.appendChild(b);}}
 bind(){const g=this.game;this.$('buildMenu').addEventListener('click',e=>{const b=e.target.closest('[data-tower]');if(b)g.chooseBuild(b.dataset.tower);});this.$('pauseBtn').onclick=()=>g.togglePause();document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>g.setSpeed(Number(b.dataset.speed)));this.$('waveBtn').onclick=()=>g.waveManager.start();this.$('upgradeBtn').onclick=()=>g.upgradeSelected();this.$('sellBtn').onclick=()=>g.sellSelected();this.$('targetSelect').onchange=e=>{if(g.selectedTower)g.selectedTower.targetMode=e.target.value;};this.$('restartBtn').onclick=()=>g.restart();this.$('muteBtn').onclick=()=>{const m=g.audio.toggleMute();this.$('muteBtn').textContent=m?'🔇':'🔊';};this.$('musicVolume').oninput=e=>g.audio.setMusic(e.target.value);this.$('sfxVolume').oninput=e=>g.audio.setSfx(e.target.value);this.$('musicVolume').value=g.audio.music;this.$('sfxVolume').value=g.audio.sfx;this.$('muteBtn').textContent=g.audio.muted?'🔇':'🔊';}
 update(){const s=this.game.state;this.$('lives').textContent=s.lives;this.$('gold').textContent=Math.floor(s.gold);this.$('wave').textContent=`${s.wave} / 30`;this.$('score').textContent=s.score.toLocaleString('fr-FR');this.$('income').textContent=`+${s.income}`;this.$('pauseBtn').textContent=s.paused?'▶':'Ⅱ';this.$('waveBtn').disabled=this.game.waveManager.active||s.wave>=30;this.$('waveBtn').textContent=this.game.waveManager.active?'Vague en cours':s.wave>=30?'Dernière vague':'Lancer vague';document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===s.speed));document.querySelectorAll('.tower-card').forEach(b=>{const d=TOWERS.find(t=>t.id===b.dataset.tower);b.classList.toggle('selected',this.game.buildChoice===b.dataset.tower);b.classList.toggle('locked',s.gold<d.cost);});this.updateTowerPanel();}
 updateTowerPanel(){const t=this.game.selectedTower,root=this.$('towerPanel');root.querySelector('.empty-selection').classList.toggle('hidden',!!t);root.querySelector('.tower-selection').classList.toggle('hidden',!t);if(!t)return;const el=ELEMENTS[t.def.element],st=t.stats;this.$('towerElement').textContent=el.name.toUpperCase();this.$('towerElement').style.color=el.color;this.$('towerName').textContent=t.def.name;this.$('towerLevel').textContent=`NIV. ${t.level}`;this.$('towerDescription').textContent=t.def.description;this.$('towerDamage').textContent=Math.round(st.damage);this.$('towerDps').textContent=(st.damage*st.rate).toFixed(1);this.$('towerRange').textContent=Math.round(st.range);this.$('towerRate').textContent=`${st.rate.toFixed(2)}/s`;this.$('towerSpecial').textContent=`${t.def.special} · ${t.kills} éliminations · ${Math.round(t.damageDone)} dégâts cumulés`;this.$('targetSelect').value=t.targetMode;const cost=t.upgradeCost;this.$('upgradeBtn').disabled=t.level>=3||!this.game.state.canSpend(cost);this.$('upgradeBtn').textContent=t.level>=3?'Niveau maximum':`Améliorer · ◈ ${cost}`;this.$('sellBtn').textContent=`Vendre · +${t.sellValue()}`;}
 banner(text){const e=this.$('waveBanner');e.textContent=text;e.classList.add('show');clearTimeout(this.bannerTimer);this.bannerTimer=setTimeout(()=>e.classList.remove('show'),1800);}
 toast(text){const e=this.$('toast');e.textContent=text;e.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>e.classList.remove('show'),1500);}
 gameOver(victory=false){this.$('gameOver').classList.remove('hidden');this.$('gameOver').querySelector('h1').textContent=victory?'Le Nexus est sauvé':'Le Nexus est tombé';this.$('gameOverStats').textContent=`Score ${this.game.state.score.toLocaleString('fr-FR')} · vague ${this.game.state.wave} · meilleur score ${this.game.bestScore.toLocaleString('fr-FR')}`;}
 hideGameOver(){this.$('gameOver').classList.add('hidden');}
 debug(text){const e=this.$('debug');e.textContent=text;e.classList.toggle('hidden',!this.game.debug);}
}
