import { TOWERS } from '../config/towers.js';import { ELEMENTS } from '../config/elements.js';import { getWave } from '../config/waves.js';import { uiIcon,elementIcon,towerIcon } from '../ui/icons.js';
const elementOrder=['fire','ice','lightning','nature','earth','arcane'];
export class UIManager{
 constructor(game){this.game=game;this.$=id=>document.getElementById(id);this.activeElement='fire';this.cache={};this.installIcons();this.buildTabs();this.buildMenu();this.bind();this.update(true);}
 installIcons(){this.$('brandIcon').innerHTML=elementIcon('arcane');this.$('lifeIcon').innerHTML=uiIcon('heart');this.$('goldIcon').innerHTML=uiIcon('coin');this.$('waveIcon').innerHTML=uiIcon('wave');this.$('scoreIcon').innerHTML=uiIcon('score');this.$('incomeIcon').innerHTML=uiIcon('income');this.$('panelRune').innerHTML=elementIcon('arcane');this.$('defeatIcon').innerHTML=elementIcon('arcane');this.$('targetIcon').innerHTML=uiIcon('target');this.$('playIcon').innerHTML=uiIcon('play');this.updateAudioIcon();}
 buildTabs(){const nav=this.$('elementTabs');nav.innerHTML='';for(const id of elementOrder){const el=ELEMENTS[id],b=document.createElement('button');b.className='element-tab';b.type='button';b.dataset.element=id;b.style.setProperty('--tab-color',el.color);b.title=el.name;b.innerHTML=elementIcon(id);nav.appendChild(b);}}
 buildMenu(){const menu=this.$('buildMenu');menu.innerHTML='';for(const t of TOWERS.filter(t=>t.element===this.activeElement)){const el=ELEMENTS[t.element],b=document.createElement('button');b.className='tower-card';b.dataset.tower=t.id;b.style.setProperty('--element',el.color);b.title=`${t.name}\n${t.description}\n${t.damage} dégâts · ${t.range} portée · ${t.rate}/s`;b.innerHTML=`<span class="tower-illustration">${towerIcon(t.id,t.element)}</span><span class="tower-card-copy"><strong>${t.name}</strong><small>${t.special}</small></span><span class="tower-cost">${uiIcon('coin')} ${t.cost}</span>`;menu.appendChild(b);}this.updateCards();}
 bind(){const g=this.game;this.$('elementTabs').addEventListener('click',e=>{const b=e.target.closest('[data-element]');if(!b)return;this.activeElement=b.dataset.element;this.buildMenu();this.updateTabs();});this.$('buildMenu').addEventListener('click',e=>{const b=e.target.closest('[data-tower]');if(b)g.chooseBuild(b.dataset.tower);});this.$('pauseBtn').onclick=()=>g.togglePause();document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>g.setSpeed(Number(b.dataset.speed)));this.$('waveBtn').onclick=()=>g.waveManager.start();this.$('upgradeBtn').onclick=()=>g.upgradeSelected();this.$('sellBtn').onclick=()=>g.sellSelected();this.$('targetSelect').onchange=e=>{if(g.selectedTower)g.selectedTower.targetMode=e.target.value;};this.$('restartBtn').onclick=()=>g.restart();this.$('muteBtn').onclick=()=>{g.audio.toggleMute();this.updateAudioIcon();};this.$('musicVolume').oninput=e=>g.audio.setMusic(e.target.value);this.$('sfxVolume').oninput=e=>g.audio.setSfx(e.target.value);this.$('musicVolume').value=g.audio.music;this.$('sfxVolume').value=g.audio.sfx;}
 updateAudioIcon(){if(this.$('muteBtn'))this.$('muteBtn').innerHTML=uiIcon(this.game.audio.muted?'mute':'audio');}
 text(id,value){if(this.cache[id]===value)return;this.cache[id]=value;this.$(id).textContent=value;}
 update(force=false){const s=this.game.state;this.text('lives',String(s.lives));this.text('gold',String(Math.floor(s.gold)));this.text('wave',`${s.wave} / 30`);this.text('score',s.score.toLocaleString('fr-FR'));this.text('income',`+${s.income}`);const paused=s.paused;const pauseKey=`pause-${paused}`;if(force||this.cache.pause!==pauseKey){this.cache.pause=pauseKey;this.$('pauseBtn').innerHTML=uiIcon(paused?'play':'pause');this.$('pauseBtn').setAttribute('aria-label',paused?'Reprendre':'Pause');}const canWave=!this.game.waveManager.active&&s.wave<30;this.$('waveBtn').disabled=!canWave;const next=s.wave<30?getWave(s.wave+1):null;this.$('waveBtn').classList.toggle('ready',canWave);this.$('waveBonus').textContent=next?`+${next.goldBonus+s.income} OR`:'TERMINÉ';this.$('waveBtn').querySelector('strong').textContent=this.game.waveManager.active?'VAGUE EN COURS':s.wave>=30?'DERNIÈRE VAGUE':'LANCER VAGUE';document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===s.speed));this.updateTabs();this.updateCards();this.updateTowerPanel();this.updateBoss();}
 updateTabs(){document.querySelectorAll('.element-tab').forEach(b=>b.classList.toggle('active',b.dataset.element===this.activeElement));}
 updateCards(){document.querySelectorAll('.tower-card').forEach(b=>{const d=TOWERS.find(t=>t.id===b.dataset.tower);if(!d)return;b.classList.toggle('selected',this.game.buildChoice===b.dataset.tower);b.classList.toggle('locked',this.game.state.gold<d.cost);});}
 updateTowerPanel(){const t=this.game.selectedTower,root=this.$('towerPanel'),sel=root.querySelector('.tower-selection');root.classList.toggle('hidden',!t);sel.classList.toggle('hidden',!t);if(!t)return;const el=ELEMENTS[t.def.element],st=t.stats;root.style.setProperty('--element',el.color);this.$('towerPortrait').style.setProperty('--element',el.color);const portraitKey=`${t.def.id}-${t.level}`;if(this.cache.portrait!==portraitKey){this.cache.portrait=portraitKey;this.$('towerPortrait').innerHTML=towerIcon(t.def.id,t.def.element);}this.text('towerElement',el.name.toUpperCase());this.$('towerElement').style.color=el.color;this.text('towerName',t.def.name);this.text('towerLevel',`NIVEAU ${t.level} · ${t.kills} ÉLIMINATIONS`);this.text('towerDescription',t.def.description);this.text('towerDamage',String(Math.round(st.damage)));this.text('towerDps',(st.damage*st.rate).toFixed(1));this.text('towerRange',String(Math.round(st.range)));this.text('towerRate',`${st.rate.toFixed(2)}/s`);this.text('towerSpecial',`${t.def.special} · ${Math.round(t.damageDone).toLocaleString('fr-FR')} dégâts infligés`);this.$('targetSelect').value=t.targetMode;const cost=t.upgradeCost,upgrade=this.$('upgradeBtn');upgrade.disabled=t.level>=3||!this.game.state.canSpend(cost);upgrade.innerHTML=t.level>=3?`NIVEAU MAX`:`${uiIcon('upgrade')} AMÉLIORER · ${cost}`;this.$('sellBtn').innerHTML=`${uiIcon('sell')} VENDRE · +${t.sellValue()}`;}
 updateBoss(){const boss=this.game.enemies.find(e=>e.def.boss&&!e.dead),root=this.$('bossHud');root.classList.toggle('hidden',!boss);if(!boss)return;this.text('bossName',boss.def.name);const ratio=Math.max(0,boss.hp/boss.maxHp);this.$('bossHealth').style.width=`${ratio*100}%`;this.text('bossValue',`${Math.ceil(boss.hp).toLocaleString('fr-FR')} / ${Math.ceil(boss.maxHp).toLocaleString('fr-FR')} PV`);}
 banner(title,subtitle=''){const e=this.$('waveBanner');this.text('waveBannerTitle',title);this.text('waveBannerSubtitle',subtitle);this.$('waveBannerKicker').textContent=title.includes('TERMINÉ')?'RÉCOMPENSE':title.includes('ARCHONTE')?'MENACE':'VAGUE';e.classList.add('show');clearTimeout(this.bannerTimer);this.bannerTimer=setTimeout(()=>e.classList.remove('show'),1900);}
 toast(text){const e=this.$('toast');e.textContent=text;e.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>e.classList.remove('show'),1500);}
 gameOver(victory=false){this.$('gameOver').classList.remove('hidden');this.text('gameOverKicker',victory?'LE NEXUS EST SAUVÉ':'LE NEXUS EST TOMBÉ');this.text('gameOverTitle',victory?'VICTOIRE':'DÉFAITE');const s=this.game.state,best=Math.max(this.game.bestScore,s.score);this.$('gameOverStats').innerHTML=`<div class="end-stat"><small>VAGUE</small><b>${s.wave}</b></div><div class="end-stat"><small>SCORE</small><b>${s.score.toLocaleString('fr-FR')}</b></div><div class="end-stat"><small>ÉLIMINATIONS</small><b>${s.kills}</b></div><div class="end-stat"><small>MEILLEUR</small><b>${best.toLocaleString('fr-FR')}</b></div>`;}
 hideGameOver(){this.$('gameOver').classList.add('hidden');}
 debug(text){const e=this.$('debug');e.textContent=text;e.classList.toggle('hidden',!this.game.debug);}
}
