import { PATH, BUILD_PADS } from '../config/map.js';
import { EventBus, WORLD_EVENTS } from '../core/EventBus.js';
import { SeededRandom, createRunSeed } from '../core/SeededRandom.js';
import { ElementalSurfaceManager } from './ElementalSurfaceManager.js';
import { MapStrategyManager } from './MapStrategyManager.js';
import { NexusStrategyManager } from './NexusStrategyManager.js';
import { RunProgressionManager } from './RunProgressionManager.js';
import { RunDirector } from './RunDirector.js';
import { TowerWorldManager } from './TowerWorldManager.js';
import { EnemyWorldManager } from './EnemyWorldManager.js';
import { RunAnalytics } from './RunAnalytics.js';
import { PerformanceBudgetManager } from './PerformanceBudgetManager.js';
import { MapMechanicRegistry, MapMechanic } from './MapMechanicFramework.js';
import { WorldStrategyRenderer } from '../render/WorldStrategyRenderer.js';
import { WorldStrategyHUD } from '../ui/WorldStrategyHUD.js';
import { installWorldStrategyAudio } from './WorldStrategyAudio.js';

export class WorldStrategyManager{
 constructor(game){
   this.game=game;this.bus=new EventBus();this.requestedSeed=this.readSeed();this.seed=this.requestedSeed||createRunSeed();this.rng=new SeededRandom(this.seed);this.battleIntensity=0;this.showHeatmap=false;this.heatmapMode=null;this.preparedWave=0;this.pendingBossRewards=null;this._preserveSeedOnce=false;this._lastWorldNow=typeof performance!=='undefined'?performance.now():0;
   installWorldStrategyAudio(game.audio);
   this.surfaces=new ElementalSurfaceManager(game,this.bus);this.map=new MapStrategyManager(game,this.bus);this.nexus=new NexusStrategyManager(game,this.bus);this.progression=new RunProgressionManager(game,this.bus,this.rng.fork('progression'));this.director=new RunDirector(game,this.bus,this.rng.fork('director'));this.towers=new TowerWorldManager(game,this.rng.fork('towers'));this.enemies=new EnemyWorldManager(game,this.bus,this.rng.fork('enemies'));this.analytics=new RunAnalytics(game);this.performance=new PerformanceBudgetManager(game);this.mechanics=new MapMechanicRegistry({game,bus:this.bus,world:this});this.mechanics.register(new MapMechanic('arcane-bastion'));
   this.renderer=new WorldStrategyRenderer(game,game.renderer.scene);this.hud=new WorldStrategyHUD(game,this);
   this.bindEvents();this.patchGame();this.patchCombat();this.patchWaves();this.patchRenderer();this.prepareNextWave();
   try{localStorage.setItem('towerdefnapst.lastSeed',this.seed);}catch{}
 }
 readSeed(){if(typeof location==='undefined')return null;const value=new URLSearchParams(location.search).get('seed');return value?.trim()?.slice(0,64)||null;}
 bindEvents(){
   this.bus.on(WORLD_EVENTS.SURFACE_CREATED,()=>{this.analytics.surfaces++;});
   this.bus.on(WORLD_EVENTS.COMBO_TRIGGERED,({id}={})=>{this.analytics.reactions++;this.analytics.onCombo(id);});
   this.bus.on(WORLD_EVENTS.OBJECTIVE_COMPLETED,()=>{this.analytics.objectives++;});
   this.bus.on(WORLD_EVENTS.NEXUS_ABILITY,()=>this.game.audio?.playWorldCue?.('nexus-ability'));
 }
 patchGame(){
   const game=this.game,originalLoop=game.loop.bind(game);game.loop=(now)=>{const raw=Math.min(.05,Math.max(0,(now-this._lastWorldNow)/1000||0));this._lastWorldNow=now;if(!game.state.paused&&!game.state.gameOver)this.update(raw*game.state.speed);else this.updatePresentation(raw);return originalLoop(now);};
   const place=game.placeTower.bind(game);game.placeTower=(x,y)=>{const pad=game.findPad(x,y);if(pad&&!this.map.isPadUsable(pad.id)){game.ui.toast(this.map.lockedPads.has(pad.id)?'Socle scellé · déblayez-le via MAP':'Socle neutralisé temporairement');return false;}const before=game.towers.length,answer=place(x,y);if(game.towers.length>before)this.progression.refreshTower(game.towers.at(-1));return answer;};
   const upgrade=game.upgradeSelected.bind(game);game.upgradeSelected=()=>{const tower=game.selectedTower,level=tower?.level;const out=upgrade();if(tower&&tower.level!==level){this.progression.refreshTower(tower);this.bus.emit(WORLD_EVENTS.TOWER_UPGRADED,{tower});}return out;};
   const specialize=game.specializeSelected.bind(game);game.specializeSelected=(id)=>{const out=specialize(id);if(game.selectedTower)this.progression.refreshTower(game.selectedTower);return out;};
   const sell=game.sellSelected.bind(game);game.sellSelected=()=>{if(game.waveManager.active)this.director.onSell();return sell();};
   game.handleEscapes=()=>this.handleEscapes();
   const restart=game.restart.bind(game);game.restart=()=>{const preserve=this._preserveSeedOnce;this._preserveSeedOnce=false;const out=restart();this.reset({preserveSeed:preserve});return out;};
   const lose=game.lose.bind(game);game.lose=()=>{const out=lose();this.hud.showBattleReport();return out;};
   const campaign=game.campaignComplete.bind(game);game.campaignComplete=()=>{const perfect=this.nexus.damageTaken<=0;const out=campaign();if(perfect){game.state.score+=2500;game.ui.banner('PERFECT DEFENSE','Le Nexus termine la campagne intact');game.audio?.playWorldCue?.('perfect-wave');}this.hud.showBattleReport();return out;};
   game.activateNexusAbility=()=>this.activateNexusAbility();game.activateShrine=id=>this.activateShrine(id);game.unlockWorldPad=()=>this.unlockPad();game.chooseArtifact=id=>this.chooseArtifact(id);game.chooseWorldWave=id=>this.chooseWave(id);game.acceptBounty=()=>this.acceptBounty();game.upgradeNexus=id=>this.upgradeNexus(id);game.toggleWorldHeatmap=()=>this.toggleHeatmap();game.restartSameSeed=()=>{this._preserveSeedOnce=true;game.restart();};
 }
 patchCombat(){
   const combat=this.game.combat,damage=combat.damage.bind(combat);combat.damage=(tower,enemy,base,isSplash=false)=>{if(!enemy||enemy.dead)return;let adjusted=base;const surface=this.surfaces.surfaceAt(enemy.x,enemy.y);if(surface?.type==='fractured'&&this.progression.artifacts.some(a=>a.id==='fracture-core'))adjusted*=1.2;const before=(enemy.hp||0)+(enemy.shield||0),plates=enemy.plates||0;damage(tower,enemy,adjusted,isSplash);const after=(enemy.hp||0)+(enemy.shield||0),dealt=Math.max(0,before-after);this.analytics.onDamage({tower,enemy,dealt,element:tower?.def?.element});if((enemy.plates||0)<plates)this.analytics.bossPlatesBrokenThisWave+=plates-(enemy.plates||0);if(dealt>0)this.surfaces.onElementHit({tower,enemy,element:tower.def.element,dealt,kind:tower.def.projectile});};
   const kill=combat.kill.bind(combat);combat.kill=(tower,enemy)=>{const wasRewarded=enemy?._rewarded;const out=kill(tower,enemy);if(enemy&&!wasRewarded&&enemy._rewarded){this.analytics.onKill({tower,enemy});this.enemies.onDeath(enemy);this.bus.emit(WORLD_EVENTS.ENEMY_KILLED,{tower,enemy});}return out;};
   const ultimate=combat.tryUltimate.bind(combat);combat.tryUltimate=tower=>{const out=ultimate(tower);if(out)this.surfaces.createFromElement(tower.def.element,tower.x,tower.y,{radius:96,duration:12,power:1.5,source:tower,persistent:true});return out;};
 }
 patchWaves(){
   const wm=this.game.waveManager,start=wm.start.bind(wm);wm.start=(manual=true)=>{if(wm.active||this.game.state.gameOver)return start(manual);if(this.director.waveChoice&&!this.director.waveChoice.selected){this.hud.showWaveChoice(this.director.waveChoice);return false;}this.applyPreparedMapEvent();const out=start(manual);if(!out)return out;this.director.applyQueue(wm.queue);for(const item of wm.queue)if(item.formationId){item.modifiers=[...(item.modifiers||[]),`formation:${item.formationId}`];}wm.pending=wm.queue.length;if(manual&&wm.lastEarlyBonus>0){const extra=Math.round(wm.lastEarlyBonus*(this.progression.earlyBonusMultiplier()-1));if(extra>0){this.game.state.gold+=extra;this.game.state.score+=extra*16;this.game.state.earlyBonus+=extra;this.game.ui.toast(`Watchtower · +${extra} or bonus`);}}this.director.onWaveStarted();this.analytics.bossPlatesBrokenThisWave=0;this.analytics.waveEliteEarlyKill=false;this.mechanics.dispatch('onWaveStart',wm.current);return out;};
   const spawn=wm.spawn.bind(wm);wm.spawn=(type,modifiers=[])=>{const applied=[...modifiers];if(this.progression.eliteBias>0&&!['boss','colossus'].includes(type)&&this.rng.next()<Math.min(.22,.06*this.progression.eliteBias))applied.push(this.rng.next()<.5?'fortified':'corrupted');const enemy=spawn(type,applied);this.enemies.onSpawn(enemy);return enemy;};
   const phase=wm.onBossPhase.bind(wm);wm.onBossPhase=(enemy,value)=>{const out=phase(enemy,value);this.map.bossMapAttack(enemy,value);this.enemies.adaptBoss(enemy,value);this.mechanics.dispatch('onBossPhase',enemy,value);this.bus.emit(WORLD_EVENTS.BOSS_PHASE_CHANGED,{enemy,phase:value});return out;};
   const complete=wm.completeWave.bind(wm);wm.completeWave=()=>{const current=wm.current,wasBoss=current?.groups?.some(g=>['boss','colossus'].includes(g.type)),beforeGold=this.game.state.gold,evaluation=this.director.evaluateWave();complete();const gained=Math.max(0,this.game.state.gold-beforeGold),mult=this.director.rewardMultiplier()*this.progression.waveRewardMultiplier(),extra=Math.max(0,Math.round(gained*(mult-1)));this.analytics.goldEarned+=gained+extra;if(extra){this.game.state.gold+=extra;this.game.state.score+=extra*10;}if(evaluation.perfect){const bonus=Math.round(20+this.game.state.wave*1.3);this.game.state.gold+=bonus;this.game.state.score+=bonus*14;this.analytics.goldEarned+=bonus;this.analytics.perfectWaves++;this.game.ui.banner('PERFECT WAVE',`Ligne intacte · +${bonus} or`);this.game.particles?.nexus?.(PATH.at(-1).x,PATH.at(-1).y);this.game.audio?.playWorldCue?.('perfect-wave');}if(evaluation.objectiveOk&&this.director.objective){const reward=this.director.objective.reward;this.game.state.gold+=reward;this.game.state.score+=reward*14;this.analytics.goldEarned+=reward;this.bus.emit(WORLD_EVENTS.OBJECTIVE_COMPLETED,{objective:this.director.objective});this.game.ui.toast(`Objectif réussi · +${reward} or`);this.game.audio?.playWorldCue?.('objective');}if(evaluation.bountyOk&&this.director.bounty){const reward=this.director.bounty.reward;this.game.state.gold+=reward;this.game.state.score+=reward*18;this.analytics.goldEarned+=reward;this.game.ui.toast(`Prime encaissée · +${reward} or`);this.game.audio?.playWorldCue?.('bounty');}this.director.onWaveCompleted();this.surfaces.onWaveComplete();this.mechanics.dispatch('onWaveComplete',current);if(this.game.state.wave>0&&this.game.state.wave%10===0)this.progression.awardTrait();if(!this.game.state.gameOver){this.prepareNextWave(!wasBoss);if(wasBoss)this.offerBossReward();}return undefined;};
 }
 patchRenderer(){const renderer=this.game.renderer,render=renderer.render.bind(renderer),lighting=renderer.updateLighting.bind(renderer);renderer.updateLighting=time=>{lighting(time);this.renderer.syncPresentation();};renderer.render=dt=>{this.renderer.sync(renderer.time+dt);return render(dt);};}
 update(dt){this.performance.update(dt);this.map.update(dt);this.nexus.update(dt);this.surfaces.maxSurfaces=Math.min(42,this.performance.surfaceLimit+10);this.surfaces.maxScars=Math.min(48,this.performance.scarLimit+8);this.surfaces.update(dt);this.enemies.update(dt);this.towers.update(dt);this.mechanics.update(dt);for(const enemy of this.game.enemies){if(enemy.adaptiveResistance){enemy.adaptiveResistance.remaining-=dt;if(enemy.adaptiveResistance.remaining<=0)enemy.adaptiveResistance=null;}}this.updateIntensity(dt);this.analytics.goldSpent=this.game.state.goldSpent||0;this.analytics.surfaces=this.surfaces.stats.created;this.analytics.reactions=this.surfaces.stats.reactions;this.hud.sync();if(!this.game.waveManager.active&&!this.game.state.gameOver)this.map.applyPendingRoute();}
 updatePresentation(dt){this.performance.update(dt);this.updateIntensity(dt);this.hud.sync();}
 updateIntensity(dt){const count=this.game.enemies?.filter(e=>!e.dead).length||0,boss=this.game.enemies?.some(e=>e.def.boss&&!e.dead),nexusRisk=1-this.game.state.lives/Math.max(1,this.game.state.maxLives||30),projectiles=this.enemies.enemyProjectiles.length;const target=Math.max(0,Math.min(1,count/36+(boss?.34:0)+nexusRisk*.28+Math.min(.14,projectiles*.025)));this.battleIntensity+=(target-this.battleIntensity)*(1-Math.exp(-dt*2.2));}
 handleEscapes(){for(const enemy of this.game.enemies){if(!enemy.escaped||enemy._counted)continue;enemy._counted=true;this.director.onEscape();const remaining=this.nexus.absorb(enemy.def.livesDamage||1);if(remaining>0)this.game.state.lives-=Math.ceil(remaining);this.game.nexusPulse=1;this.game.particles.nexus(PATH.at(-1).x,PATH.at(-1).y);this.game.audio.playUi('leak');this.game.renderer.kickCamera(enemy.def.boss?.07:.025,PATH.at(-1).x,PATH.at(-1).y);if(this.game.state.lives<=0){this.game.state.lives=0;this.game.lose();break;}}}
 damageNexus(amount){const remaining=this.nexus.absorb(amount);if(remaining>0)this.game.state.lives=Math.max(0,this.game.state.lives-Math.ceil(remaining));this.game.nexusPulse=1;if(this.game.state.lives<=0&&!this.game.state.gameOver)this.game.lose();return remaining;}
 prepareNextWave(show=false){const next=this.game.state.wave+1;if(next===this.preparedWave||this.game.state.gameOver)return;this.preparedWave=next;const plan=this.director.prepareBetweenWaves(next);if(plan.mapEvent?.route)this.map.announceRoute(plan.mapEvent.route);if(show){if(plan.waveChoice)this.hud.showWaveChoice(plan.waveChoice);else if(plan.bounty)this.hud.showBounty(plan.bounty);}this.hud.sync(true);}
 applyPreparedMapEvent(){const event=this.director.nextMapEvent;if(!event)return;if(event.route)this.map.applyPendingRoute();if(event.surface==='wet')this.surfaces.addWeather('wet',PATH.filter((_,i)=>i%2===1).slice(0,5).map(p=>({...p,radius:95,duration:22})));if(event.surface==='arcane')for(const p of PATH.filter((_,i)=>[2,4,6,8].includes(i)))this.surfaces.create('arcane',p.x,p.y,{radius:78,duration:18,power:.9});this.bus.emit(WORLD_EVENTS.MAP_EVENT,{event});this.game.ui.banner(event.name.toUpperCase(),event.warning);this.game.audio?.playWorldCue?.('map-event');}
 offerBossReward(){const pool=[{id:'gold',name:'TRÉSOR DE GUERRE',hint:'+ or immédiat'},{id:'artifact',name:'ARTEFACT',hint:'choix de build permanent'},{id:'nexus',name:'RENFORCER LE NEXUS',hint:'shield + vies'},{id:'pad',name:'NOUVEAU SOCLE',hint:'débloque un emplacement'}];this.pendingBossRewards=this.rng.shuffle(pool).slice(0,3);this.hud.showBossRewardChoice?.(this.pendingBossRewards);}
 chooseBossReward(id){if(!this.pendingBossRewards?.some(r=>r.id===id))return false;this.pendingBossRewards=null;if(id==='gold'){const reward=220+this.game.state.wave*6;this.game.state.gold+=reward;this.game.state.score+=reward*12;this.analytics.goldEarned+=reward;this.game.ui.toast(`Trésor de guerre · +${reward} or`);}else if(id==='artifact')this.hud.showArtifactChoice(this.progression.artifactChoices(3));else if(id==='nexus'){this.nexus.addPermanentShield(8);this.game.state.maxLives+=2;this.game.state.lives=Math.min(this.game.state.maxLives,this.game.state.lives+2);this.game.ui.toast('Nexus renforcé · +8 shield · +2 vies');}else if(id==='pad')this.unlockPad(true);return true;}
 chooseArtifact(id){const artifact=this.progression.chooseArtifact(id);if(artifact){this.hud.sync(true);return true;}return false;}
 chooseWave(id){const ok=this.director.chooseWave(id);if(ok){this.game.ui.toast(`Route tactique · ${id.toUpperCase()}`);this.hud.sync(true);}return ok;}
 acceptBounty(){const ok=this.director.acceptBounty();if(ok){this.game.audio?.playWorldCue?.('bounty');this.game.ui.toast(`Contrat accepté · ${this.director.bounty.name}`);this.hud.sync(true);}return ok;}
 activateShrine(id){const shrine=this.map.activateShrine(id);if(shrine){this.progression.refreshAllTowers();this.game.ui.toast(`${shrine.name} activé`);return true;}this.game.ui.toast('Or insuffisant ou sanctuaire déjà actif');return false;}
 unlockPad(free=false){if(!this.map.lockedPads.size)return false;const cost=180+Math.max(0,4-this.map.lockedPads.size)*45;if(!free&&!this.game.state.spend(cost)){this.game.ui.toast('Or insuffisant pour déblayer le socle');return false;}const ok=this.map.unlockAnyPad();if(ok)this.game.ui.toast(`Socle restauré${free?'':` · ${cost} or`}`);return ok;}
 upgradeNexus(id){const out=this.progression.upgradeNexus(id);if(out){this.game.ui.toast(`${out.def.name} · niveau ${out.level}`);this.hud.sync(true);return true;}this.game.ui.toast('Upgrade Nexus indisponible');return false;}
 activateNexusAbility(){const ok=this.nexus.activateAbility();if(ok)this.hud.sync(true);return ok;}
 toggleHeatmap(){const modes=[null,'deaths','damage','coverage'];const index=modes.indexOf(this.heatmapMode);this.heatmapMode=modes[(index+1)%modes.length];this.showHeatmap=Boolean(this.heatmapMode);this.hud.sync(true);return this.heatmapMode;}
 ascendSelectedLegendary(id){const out=this.progression.ascendTower(this.game.selectedTower,id);if(out){this.game.audio?.playWorldCue?.('legendary');this.game.ui.toast(`${out.name} déverrouillée`);return true;}return false;}
 reset({preserveSeed=false}={}){this.renderer?.setHeatmapVisible?.(false);this.showHeatmap=false;this.heatmapMode=null;if(!preserveSeed&&!this.requestedSeed)this.seed=createRunSeed();this.rng=new SeededRandom(this.seed);this.progression.rng=this.rng.fork('progression');this.director.rng=this.rng.fork('director');this.towers.rng=this.rng.fork('towers');this.enemies.rng=this.rng.fork('enemies');this.surfaces.reset();this.map.reset();this.nexus.reset();this.progression.reset();this.director.reset();this.towers.reset();this.enemies.reset();this.analytics.reset();this.performance.reset();this.mechanics.reset();this.battleIntensity=0;this.preparedWave=0;this.pendingBossRewards=null;try{localStorage.setItem('towerdefnapst.lastSeed',this.seed);}catch{}this.prepareNextWave();this.hud.hideModal();this.hud.sync(true);}
}
