import { GameState } from './GameState.js';import { TOWER_BY_ID } from '../config/towers.js';import { BUILD_PADS,PATH } from '../config/map.js';import { Tower } from '../entities/Tower.js';import { WaveManager } from '../systems/WaveManager.js';import { CombatSystem } from '../systems/CombatSystem.js';import { ParticleSystem } from '../systems/ParticleSystem.js';import { AudioManager } from '../systems/AudioManager.js';import { UIManager } from '../systems/UIManager.js';import { Renderer } from '../render/Renderer.js';
export class Game{
 constructor(canvas){this.canvas=canvas;this.state=new GameState();this.towers=[];this.enemies=[];this.projectiles=[];this.selectedTower=null;this.buildChoice=null;this.hoverPad=null;this.hoverWorld=null;this.debug=false;this.nexusPulse=0;this.bestScore=Number(localStorage.getItem('towerdefnapst.bestScore')||0);this.audio=new AudioManager();this.particles=new ParticleSystem();this.waveManager=new WaveManager(this);this.combat=new CombatSystem(this);this.renderer=new Renderer(this,canvas);this.ui=new UIManager(this);this.last=performance.now();this.fps=60;this.frames=0;this.fpsTime=0;this.uiClock=0;this.bindInput();requestAnimationFrame(t=>this.loop(t));}
 bindInput(){this.canvas.addEventListener('mousemove',e=>{const p=this.renderer.screenToWorld(e.clientX,e.clientY);this.hoverWorld=p;this.hoverPad=this.findPad(p.x,p.y);});this.canvas.addEventListener('mouseleave',()=>{this.hoverPad=null;this.hoverWorld=null;});this.canvas.addEventListener('click',e=>{this.audio.ensure();const p=this.renderer.screenToWorld(e.clientX,e.clientY),tower=this.findTower(p.x,p.y);if(tower){this.selectedTower=tower;this.buildChoice=null;this.ui.update(true);return;}if(this.buildChoice){this.placeTower(p.x,p.y);return;}this.selectedTower=null;this.ui.update(true);});window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();this.togglePause();}if(e.key.toLowerCase()==='d'){this.debug=!this.debug;}if(e.key==='Escape'){this.buildChoice=null;this.selectedTower=null;this.ui.update(true);}if(['1','2','3'].includes(e.key))this.setSpeed(Number(e.key));});}
 getBuildRange(){return this.buildChoice&&TOWER_BY_ID[this.buildChoice]?TOWER_BY_ID[this.buildChoice].range:80;}
 findPad(x,y){return BUILD_PADS.find(p=>(p.x-x)**2+(p.y-y)**2<=p.r**2)||null;}
 findTower(x,y){return [...this.towers].reverse().find(t=>(t.x-x)**2+(t.y-y)**2<=35**2)||null;}
 chooseBuild(id){const def=TOWER_BY_ID[id];if(!def)return;if(!this.state.canSpend(def.cost)){this.ui.toast('Or insuffisant');return;}this.selectedTower=null;this.buildChoice=this.buildChoice===id?null:id;this.ui.update(true);}
 placeTower(x,y){const def=TOWER_BY_ID[this.buildChoice],pad=this.findPad(x,y);if(!def||!pad){this.ui.toast('Placez la défense sur un socle runique');return;}if(this.towers.some(t=>t.pad.id===pad.id)){this.ui.toast('Ce socle est déjà occupé');return;}if(!this.state.spend(def.cost)){this.ui.toast('Or insuffisant');return;}const tower=new Tower(def,pad);this.towers.push(tower);this.selectedTower=tower;this.buildChoice=null;this.audio.play('build');this.particles.build(pad.x,pad.y,def.element);this.ui.toast(`${def.name} déployée`);this.ui.update(true);}
 upgradeSelected(){const t=this.selectedTower;if(!t||t.level>=3)return;const cost=t.upgradeCost;if(!this.state.spend(cost)){this.ui.toast('Or insuffisant');return;}t.upgrade();this.audio.play('upgrade');this.particles.upgrade(t.x,t.y,t.def.element);this.ui.toast(`${t.def.name} · niveau ${t.level}`);this.ui.update(true);}
 sellSelected(){const t=this.selectedTower;if(!t)return;const v=t.sellValue();this.state.gold+=v;this.particles.sell(t.x,t.y);this.towers=this.towers.filter(x=>x!==t);this.selectedTower=null;this.ui.toast(`Défense recyclée · +${v} or`);this.ui.update(true);}
 togglePause(){if(this.state.gameOver)return;this.state.paused=!this.state.paused;this.ui.update(true);}
 setSpeed(v){this.state.speed=v;this.ui.update(true);}
 loop(now){const raw=Math.min(.05,(now-this.last)/1000||0);this.last=now;this.frames++;this.fpsTime+=raw;this.uiClock+=raw;if(this.fpsTime>=.5){this.fps=Math.round(this.frames/this.fpsTime);this.frames=0;this.fpsTime=0;}this.nexusPulse=Math.max(0,this.nexusPulse-raw*1.7);if(!this.state.paused&&!this.state.gameOver){const dt=raw*this.state.speed;this.state.elapsed+=dt;this.waveManager.update(dt);for(const e of this.enemies)e.update(dt);this.handleEscapes();this.claimDotDeaths();this.combat.update(dt);for(const p of this.projectiles)p.update(dt,proj=>this.combat.impact(proj));this.projectiles=this.projectiles.filter(p=>!p.dead);this.enemies=this.enemies.filter(e=>!e.dead);this.particles.update(dt);}else this.particles.update(raw*.3);this.renderer.render(raw);if(this.uiClock>.08){this.uiClock=0;this.ui.update();this.ui.debug(`FPS ${this.fps}\nEnnemis ${this.enemies.length}\nProjectiles ${this.projectiles.length}\nParticules ${this.particles.items.length}\nTours ${this.towers.length}\nVitesse x${this.state.speed}\nTemps ${this.state.elapsed.toFixed(1)} s`);}requestAnimationFrame(t=>this.loop(t));}
 claimDotDeaths(){for(const e of this.enemies){if(e.dead&&!e.escaped&&!e._rewarded)this.combat.kill(e.killedBy||null,e);}}
 handleEscapes(){for(const e of this.enemies){if(!e.escaped||e._counted)continue;e._counted=true;this.state.lives-=e.def.livesDamage||1;this.nexusPulse=1;this.particles.nexus(PATH.at(-1).x,PATH.at(-1).y);this.audio.play('leak');if(this.state.lives<=0){this.state.lives=0;this.lose();break;}}}
 lose(){this.state.gameOver=true;this.persistScore();this.ui.gameOver(false);}
 win(){this.state.gameOver=true;this.state.victory=true;this.state.score+=5000;this.persistScore();this.ui.gameOver(true);}
 persistScore(){if(this.state.score>this.bestScore){this.bestScore=this.state.score;localStorage.setItem('towerdefnapst.bestScore',String(this.bestScore));}}
 restart(){this.state.reset();this.towers=[];this.enemies=[];this.projectiles=[];this.selectedTower=null;this.buildChoice=null;this.hoverPad=null;this.waveManager.active=false;this.waveManager.queue=[];this.waveManager.current=null;this.nexusPulse=0;this.particles.clear();this.ui.hideGameOver();this.ui.toast('Le Nexus est de nouveau défendu');this.ui.update(true);}
}
